### ISSUE TITLE
OP_REQUIRES failed at reshape_op.h:57 : Invalid argument: Size 0 must be non-negative, not -1113764467

### ISSUE THREAD

**Issue by oleid** [ROCmSoftwarePlatform/tensorflow-upstream#1089]
**System information**
I'm using the official rocm/tensorflow docker container on ArchLinux with their kernel 5.8 - so I'm on upstream driver.
GPU is  Radeon 480RX on a first generation Ryzen 1800X.

I'm using the official docker image for reproducability.
```
sudo docker run -it \
      --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined \
      --group-add video  --volume $PWD:/data rocm/tensorflow
```

**Describe the current behavior**

I tried to train a small network:

```
Found 497 images belonging to 2 classes.
Found 7156 images belonging to 2 classes.
Training samples: 497
Testing samples: 7156
2020-08-21 08:46:34.785973: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libamdhip64.so
2020-08-21 08:46:35.223740: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1734] Found device 0 with properties: 
pciBusID: 0000:08:00.0 name: Ellesmere [Radeon RX 470/480/570/570X/580/580X]     ROCm AMD GPU ISA: gfx803
coreClock: 1.26GHz coreCount: 32 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 0B/s
2020-08-21 08:46:35.281865: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocblas.so
2020-08-21 08:46:35.293227: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libMIOpen.so
2020-08-21 08:46:35.421535: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocfft.so
2020-08-21 08:46:35.433313: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocrand.so
2020-08-21 08:46:35.433636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-08-21 08:46:35.440756: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3844125000 Hz
2020-08-21 08:46:35.441358: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x511d2e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-21 08:46:35.441376: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-21 08:46:35.443029: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x4df9170 initialized for platform ROCM (this does not guarantee that XLA will be used). Devices:
2020-08-21 08:46:35.443047: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Ellesmere [Radeon RX 470/480/570/570X/580/580X], AMDGPU ISA version: gfx803
2020-08-21 08:46:35.805626: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1734] Found device 0 with properties: 
pciBusID: 0000:08:00.0 name: Ellesmere [Radeon RX 470/480/570/570X/580/580X]     ROCm AMD GPU ISA: gfx803
coreClock: 1.26GHz coreCount: 32 deviceMemorySize: 4.00GiB deviceMemoryBandwidth: 0B/s
2020-08-21 08:46:35.805718: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocblas.so
2020-08-21 08:46:35.805740: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libMIOpen.so
2020-08-21 08:46:35.805764: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocfft.so
2020-08-21 08:46:35.805790: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocrand.so
2020-08-21 08:46:35.805957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-08-21 08:46:35.806004: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-21 08:46:35.806021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-08-21 08:46:35.806035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-08-21 08:46:35.806295: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3796 MB memory) -> physical GPU (device: 0, name: Ellesmere [Radeon RX 470/480/570/570X/580/580X], pci bus id: 0000:08:00.0)
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d (Conv2D)              (None, 100, 100, 8)       80        
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 50, 50, 8)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 50, 50, 16)        1168      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 25, 25, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 25, 25, 32)        4640      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 12, 12, 64)        18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
flatten (Flatten)            (None, 2304)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               295040    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 129       
=================================================================
Total params: 319,553
Trainable params: 319,553
Non-trainable params: 0
_________________________________________________________________
2020-08-21 08:46:38.469636: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:46:38.484956: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
Epoch 1/30
2020-08-21 08:46:40.368139: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:46:40.382708: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:46:40.386057: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:46:40.390333: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:46:40.410480: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library librocblas.so
2020-08-21 08:46:42.208745: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libMIOpen.so
MIOpen(HIP): Warning [Prefetch] File is unreadable: /opt/rocm-3.7.0/miopen/share/miopen/db/gfx803_32.HIP.fdb.txt
 3/31 [=>............................] - ETA: 0s - accuracy: 0.7500 - loss: 0.63432020-08-21 08:47:22.763526: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at reshape_op.h:57 : Invalid argument: Size 0 must be non-negative, not -1113764467
Traceback (most recent call last):
  File "learn_for_loco_classification.py", line 93, in <module>
    epochs = epochs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 807, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Size 0 must be non-negative, not -1113764467
	 [[node gradient_tape/binary_crossentropy/Reshape (defined at learn_for_loco_classification.py:93) ]] [Op:__inference_train_function_1088]

Function call stack:
train_function

2020-08-21 08:47:22.870540: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
```

This is how the container is run:

`docker run -it --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video  --volume $PWD:/data rocm/tensorflow`

**Describe the expected behavior**

When not passing `--device=/dev/kfd --device=/dev/dri ` to the container, the CPU backend is used, training works fine:

```
Found 497 images belonging to 2 classes.
Found 7156 images belonging to 2 classes.
Training samples: 497
Testing samples: 7156
2020-08-21 08:49:43.404401: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libamdhip64.so
2020-08-21 08:49:43.404662: E tensorflow/stream_executor/rocm/rocm_driver.cc:982] could not retrieve ROCM device count: HIP_ERROR_NoDevice
2020-08-21 08:49:43.404692: E tensorflow/stream_executor/rocm/rocm_driver.cc:982] could not retrieve ROCM device count: HIP_ERROR_NoDevice
2020-08-21 08:49:43.428180: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3844125000 Hz
2020-08-21 08:49:43.428947: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562c260 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-21 08:49:43.428972: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-21 08:49:43.431009: E tensorflow/stream_executor/rocm/rocm_driver.cc:982] could not retrieve ROCM device count: HIP_ERROR_NoDevice
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
conv2d (Conv2D)              (None, 100, 100, 8)       80        
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 50, 50, 8)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 50, 50, 16)        1168      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 25, 25, 16)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 25, 25, 32)        4640      
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 12, 12, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 12, 12, 64)        18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
flatten (Flatten)            (None, 2304)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               295040    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 129       
=================================================================
Total params: 319,553
Trainable params: 319,553
Non-trainable params: 0
_________________________________________________________________
2020-08-21 08:49:43.577347: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:49:43.583715: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
Epoch 1/30
2020-08-21 08:49:43.949978: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:49:43.977251: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:49:43.980287: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:49:43.982250: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
30/31 [============================>.] - ETA: 0s - accuracy: 0.7441 - loss: 0.52212020-08-21 08:49:45.166087: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:49:45.173856: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:49:45.329348: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:49:45.333580: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:49:45.335674: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:49:45.336967: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
31/31 [==============================] - 6s 201ms/step - accuracy: 0.7526 - loss: 0.5084 - val_accuracy: 0.9891 - val_loss: 0.0998
[...]
31/31 [==============================] - ETA: 0s - accuracy: 0.9979 - loss: 0.00892020-08-21 08:51:56.117083: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:51:56.124138: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:51:56.127283: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:51:56.128736: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
2020-08-21 08:51:56.129791: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:505] ROCm Fusion is enabled.
31/31 [==============================] - 4s 141ms/step - accuracy: 0.9979 - loss: 0.0089 - val_accuracy: 1.0000 - val_loss: 1.0001e-04
```

**Standalone code to reproduce the issue**

The network is really trivial:

```python
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Dropout, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image

import os
import numpy as np

img_width, img_height = 100, 100
batch_size = 16
epochs = 30
input_shape = (img_width, img_height, 1)

data_dir = "."
training_dir = os.path.join(data_dir, "training")
testing_dir = os.path.join(data_dir, "testing")


# PLEASE NOTE: the image generator and their corresponding data generators
# get the classification of the images from the directory structure below data_dir
training_image_generator = ImageDataGenerator(rescale=1./255,
	horizontal_flip=True, rotation_range=45, zoom_range=0.3)

testing_image_generator = ImageDataGenerator(rescale=1./255) # no augmentation here
	
training_datagen = training_image_generator.flow_from_directory(
	training_dir, target_size=(img_width, img_height), batch_size=batch_size,
	color_mode='grayscale', classes=["car", "loco"],
	class_mode='binary', shuffle=True, seed=None)

testing_datagen = testing_image_generator.flow_from_directory(
	testing_dir, target_size=(img_width, img_height), batch_size=batch_size,
	color_mode='grayscale', classes=["car", "loco"],
	class_mode='binary', shuffle=True, seed=None)


print("Training samples: %i" % training_datagen.samples)
print("Testing samples: %i" % testing_datagen.samples)

##########

model = Sequential([
	Conv2D(8, 3, activation='relu', input_shape=input_shape, padding="same"),
	MaxPooling2D(padding="valid"),

	Conv2D(16, 3, activation='relu', padding="same"),
	MaxPooling2D(padding="valid"),
	Conv2D(32, 3, activation='relu', padding="same"),
	MaxPooling2D(padding="valid"),
	Conv2D(64, 3, activation='relu', padding="same"),
	MaxPooling2D(padding="valid"),

	Flatten(),
	Dense(128, activation='relu'),
	Dropout(0.5),
	Dense(1, activation='sigmoid'),
])

model.compile(optimizer='adam',
		loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),
		metrics=['accuracy'])

model.summary()


model.fit(
	training_datagen,
	steps_per_epoch = training_datagen.samples // batch_size,
	validation_data = testing_datagen, 
	validation_steps = testing_datagen.samples // batch_size,
	epochs = epochs)
```

**Comment by Djip007** [comment]
Is the dataset public? can I download it somewhere?

**Comment by oleid** [comment]
Sadly not. But let me see if I can reproduce it with a public dataset...

**Comment by oleid** [comment]
This is a minimal example based on `mnist` dataset. Trouble is: I cannot reproduce the original error (even with the non-public dataset)  :confused:  - training seems to work. Well, apart from a hard freeze of my machine after a few epochs. But loss sinks and accuracy converges slowly to 1. So I guess we can close this issue. Sorry for the noise.

```python
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, Dropout, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image

import os
import numpy as np

img_width, img_height = 100, 100
batch_size = 16
epochs = 30
input_shape = (img_width, img_height, 1)

##########
def relabel_as_odd_or_even(i):
	return 0 if i % 2 == 0 else 1


def prepare_image(im):
  # scale four times the size and cut out 100x100 image
  scaled = np.kron(im, np.ones((4,4)))
  resized = scaled[:img_width, :img_height] / 255.0
  return resized

###########

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = np.expand_dims(np.stack([prepare_image(im.reshape(28,28)) for im in x_train]), axis=-1)
x_test = np.expand_dims(np.stack([prepare_image(im.reshape(28,28)) for im in x_test]), axis=-1)

y_train = np.array([relabel_as_odd_or_even(i) for i in y_train])
y_test = np.array([relabel_as_odd_or_even(i) for i in y_test])

model = Sequential([
	Conv2D(8, 3, activation='relu', input_shape=input_shape, padding="same"),
	MaxPooling2D(padding="valid"),

	Conv2D(16, 3, activation='relu', padding="same"),
	MaxPooling2D(padding="valid"),
	Conv2D(32, 3, activation='relu', padding="same"),
	MaxPooling2D(padding="valid"),
	Conv2D(64, 3, activation='relu', padding="same"),
	MaxPooling2D(padding="valid"),

	Flatten(),
	Dense(128, activation='relu'),
	Dropout(0.5),
	Dense(1, activation='sigmoid'),
])

model.compile(optimizer='adam',
		loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),
		metrics=['accuracy'])

model.summary()

model.fit(
	x_train,
	y_train, 
	steps_per_epoch = len(x_train) // batch_size,
	validation_data = (x_test, y_test), 
	validation_steps = len(x_test) // batch_size,
	epochs = epochs)
```

**Comment by jerryyin** [comment]
Thanks for confirming ROCm 3.7 works for you. Yes, this is an issue exposed in ROCm 3.5 runtime and the release of ROCm 3.7 fixed it. Closing the issue now.
