### ISSUE TITLE
tensorflow-text import ERROR

### ISSUE THREAD

**Issue by kglapiak** [ROCmSoftwarePlatform/tensorflow-upstream#1304]
**System information**
-Image: rocm4.0.1-tf2.3-dev/ rocm4.0.1-tf2.4-dev
-Tensorflow: 2.3.3 / 2.40

Hello,

I try install package tensorflow_text:
```pip3 install tensorflow-text==2.3.0 / tensorflow-text==2.4.0```

Installation is succesfull without any errors and warnings.

But after import 
``` import tensorflow_text as text ``` 

In both images occures error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/__init__.py", line 21, in <module>
    from tensorflow_text.python import metrics
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/__init__.py", line 20, in <module>
    from tensorflow_text.python.metrics.text_similarity_metric_ops import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/text_similarity_metric_ops.py", line 28, in <module>
    gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so'))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

```

This situation in normal tensorflow without ROCm distribution dosen't  happend, so problem is in this distribution, not tensorflow in general.

Please fix this bug

**Comment by kglapiak** [comment]
In new version rocm4.1.1 same problem

**Comment by lucbruni-amd** [comment]
This is no longer a problem as of now.

Image: rocm/tensorflow:latest
ROCm: 6.3.2
TensorFlow: 2.17.0

Installation (`pip install tensorflow_text`) and import of `tensorflow_text` were successful.

Closing as resolved. Please feel free to open a new issue if a related problem persists on newer versions. Thanks!
