### ISSUE TITLE
import fails after installation.

### ISSUE THREAD

**Issue by gggh000** [ROCmSoftwarePlatform/tensorflow-upstream#1382]
Ubuntu 1804:
root@sriov-guest:~# python3 --version
Python 3.6.9

Installed as usual: 
pip3 install --user tensorflow-rocm --upgrade

There seems online discussion that it happens when CWD is tensorflow source but that should not be the cause of import. 

```
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
tensorflow-estimator    2.4.0
tensorflow-rocm         2.4.3
termcolor               1.1.0
testresources           2.0.0
traceback2              1.4.0
typing-extensions       3.7.4.3
ubuntu-advantage-tools  27.0
ubuntu-drivers-common   0.0.0
ufw                     0.36
unattended-upgrades     0.1
unittest2               1.1.0
urllib3                 1.22
usb-creator             0.3.3
verboselogs             1.7
wadllib                 1.3.2
Werkzeug                2.0.1
wheel                   0.36.2
wrapt                   1.12.1
xkit                    0.0.0
zipp                    3.4.1
zope.interface          4.3.2
root@sriov-guest:/git.co/tensorflow# python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/git.co/tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/git.co/tensorflow/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/git.co/tensorflow/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
ImportError: cannot import name 'function_pb2'
>>> quit()

```

**Comment by gggh000** [comment]
after apt-get update && apt dist-upgrade + apt install python3-pip python3-setuptools + rocm full installation, it appears to work.

**Comment by gggh000** [comment]
Fresh installation still failing:
```
-bazel/linux-x86_64/crypto/fipsmodule/x86_64-mont5.o python_build/temp.linux-x86_64-3.6/third_party/boringssl-with-bazel/linux-x86_64/crypto/fipsmodule/x86_64-mont.o python_build/temp.linux-x86_64-3.6/third_party/boringssl-with-bazel/src/crypto/hrss/asm/poly_rq_mul.o -lrt -lm -o python_build/lib.linux-x86_64-3.6/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so -lpthread -Wl,-wrap,memcpy -static-libgcc
    Traceback (most recent call last):
      File "/tmp/pip-build-3myzovp3/grpcio/src/python/grpcio/commands.py", line 264, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/root/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 203, in build_extension
        if ext._needs_stub:
    AttributeError: 'Extension' object has no attribute '_needs_stub'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3myzovp3/grpcio/setup.py", line 465, in <module>
        cmdclass=COMMAND_CLASS,
      File "/root/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-3myzovp3/grpcio/src/python/grpcio/commands.py", line 267, in build_extensions
        support.diagnose_build_ext_error(self, error, formatted_exception)
      File "/tmp/pip-build-3myzovp3/grpcio/src/python/grpcio/support.py", line 118, in diagnose_build_ext_error
        diagnostic(build_ext, error)
      File "/tmp/pip-build-3myzovp3/grpcio/src/python/grpcio/support.py", line 98, in diagnose_attribute_error
        "We expect a missing `_needs_stub` attribute from older versions of "
    commands.CommandError: We expect a missing `_needs_stub` attribute from older versions of setuptools. Consider upgrading setuptools.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3myzovp3/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lrbza8vl-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-3myzovp3/grpcio/

```

**Comment by gggh000** [comment]
setuptools upgrade warning is misleading as i am using latest one: 
-bazel/linux-x86_64/crypto/fipsmodule/x86_64-mont5.o python_build/temp.linux-x86_64-3.6/third_party/boringssl-with-bazel/linux-x86_64/crypto/fipsmodule/x86_64-mont.o python_build/temp.linux-x86_64-3.6/third_party/boringssl-with-bazel/src/crypto/hrss/asm/poly_rq_mul.o -lrt -lm -o python_build/lib.linux-x86_64-3.6/grpc/_cython/cygrpc.cpython-36m-x86_64-linux-gnu.so -lpthread -Wl,-wrap,memcpy -static-libgcc
    Traceback (most recent call last):
      File "/tmp/pip-build-3myzovp3/grpcio/src/python/grpcio/commands.py", line 264, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/root/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 203, in build_extension
        if ext._needs_stub:
    AttributeError: 'Extension' object has no attribute '_needs_stub'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3myzovp3/grpcio/setup.py", line 465, in <module>
        cmdclass=COMMAND_CLASS,
      File "/root/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/root/.local/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-3myzovp3/grpcio/src/python/grpcio/commands.py", line 267, in build_extensions
        support.diagnose_build_ext_error(self, error, formatted_exception)
      File "/tmp/pip-build-3myzovp3/grpcio/src/python/grpcio/support.py", line 118, in diagnose_build_ext_error
        diagnostic(build_ext, error)
      File "/tmp/pip-build-3myzovp3/grpcio/src/python/grpcio/support.py", line 98, in diagnose_attribute_error
        "We expect a missing `_needs_stub` attribute from older versions of "
    commands.CommandError: We expect a missing `_needs_stub` attribute from older versions of setuptools. Consider upgrading setuptools.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3myzovp3/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lrbza8vl-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-3myzovp3/grpcio/

**Comment by sunway513** [comment]
Hi @gggh000 , can you provide a Dockerfile to reproduce the failures you have observed, in case you're expecting inputs from the ROCm team?

**Comment by ppanchad-amd** [comment]
Hi @gggh000. Closing ticket due to lack of activity. Please feel free to open a new ticket if you have any questions/issues with the latest ROCm. Thanks!
