### ISSUE TITLE
Rocm 4.2 Radeon VII Errors

### ISSUE THREAD

**Issue by roblem** [ROCmSoftwarePlatform/tensorflow-upstream#1388]
**System information**

-  **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**

     Yes. See example below.

-  **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**

    Ubuntu 20.04.2 HWE (note I have tried also on 20.04.2)

- **Video drivers and ROCm**
   I have tried quite a few things related to rock-dkms, upstream and amdgpu drivers downloaded from amd, in an effort to get things going.  I am quite sure that I've completely uninstalled everything when trying these combinations. I am including details here because it isn't clear how (or if) Radeon VII ROCm tensorflow operations can work given available guides, and probably I have made an error installing things.  Running tf code on
   - upstream video driver with no `rock-dkms` installed yields 
     ```
     HSA Error: Incompatible kernel and userspace, Vega 20 [Radeon VII]  disabled. Upgrade amdgpu.
     ```
     when running lots of tensorflow ops
   - upstream video driver with `rock-dkms` installed also yields
     ```
     HSA Error: Incompatible kernel and userspace, Vega 20 [Radeon VII]  disabled. Upgrade amdgpu.
     ```
   - I took the above error message "upgrade amdgpu" to mean install the amd driver downloaded from amd, using `amdgpu-install` along with pieces of `rocm` that supplies things like `rccl`, `rocrand`, `rocblas`, and `miopen-hip` so that tensorflow appears to startup as I was used to seeing in the <v4.1 days.  Note, in this configuration, I did not install `rock-dkms`, as the amd downloaded driver apparently has this piece included.  I am using the amd driver version 21.10-1247438-ubuntu-20.04.

   All of the errors reported below are using this configuration.

**Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**

None

**TensorFlow installed from (source or binary)**

`pip install tensorflow-rocm`

**TensorFlow version (use command below)**

2.4.3

**Python version**

Python 3.7.10

**GPU model and memory**

2 Radeon VII's :  ROCm AMDGPU Arch: gfx906:sramecc-:xnack-

**TF Git version**

v2.4.1-28-g551d9173703 2.4.3

**Describe the current behavior**

XLA functions (using `experimental_compile=True` on GPU) fail with the error message

```
tensorflow.python.framework.errors_impl.InternalError: unable to find ld.lld in PATH: No such file or directory [Op:__inference_simple_function_xla_11]
```

XLA functions on CPU compile without problems.

**Standalone code to reproduce the issue**

```python
import sys
import os
import tensorflow as tf

print(os.system('uname -a'))
print("Running in:", sys.executable)
print("TF devices: ", tf.config.list_physical_devices())

print('\n'*3)

@tf.function
def simple_function(x):
  return x**2

print('\n'*3)  
with tf.device('/GPU:0'):
    v = simple_function(2.) # runs on gpu and returns result

print("\nFunction on GPU returns: ", v)

@tf.function(experimental_compile=True)
def simple_function_xla(x):
    return x**2

print('\n')  
with tf.device('/CPU:0'):
    vxla = simple_function_xla(2.) # compiles xla and returns result

print("\nFunction on CPU with XLA returns: ", vxla)
print('\n')

vxla = simple_function_xla(2.)  # fails with error
print("Function on GPU with XLA returns: ", vxla)
```
Using some other code that is alot less trivial than this, leads to errors like this:
```
tensorflow.python.framework.errors_impl.InternalError: bitcode module not found at ./hc.bc [Op:__inference_ols_loglike_43]
```

**Other info / logs** 

Trace:
```
$ python simple_function.py 
Linux sopris 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
0
Running in: /home/robhicks/anaconda3/envs/tf-rocm-3.7/bin/python
2021-06-17 04:41:40.768815: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-17 04:41:40.768897: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libamdhip64.so
2021-06-17 04:41:40.836629: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1734] Found device 0 with properties: 
pciBusID: 0000:19:00.0 name: Vega 20 [Radeon VII]     ROCm AMDGPU Arch: gfx906:sramecc-:xnack-
coreClock: 1.801GHz coreCount: 60 deviceMemorySize: 15.98GiB deviceMemoryBandwidth: 953.67GiB/s
2021-06-17 04:41:40.836664: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1734] Found device 1 with properties: 
pciBusID: 0000:b5:00.0 name: Vega 20 [Radeon VII]     ROCm AMDGPU Arch: gfx906:sramecc-:xnack-
coreClock: 1.801GHz coreCount: 60 deviceMemorySize: 15.98GiB deviceMemoryBandwidth: 953.67GiB/s
2021-06-17 04:41:40.839778: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocblas.so
2021-06-17 04:41:40.840804: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libMIOpen.so
2021-06-17 04:41:40.855348: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libhipfft.so
2021-06-17 04:41:40.855527: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocrand.so
2021-06-17 04:41:40.855603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
TF devices:  [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

2021-06-17 04:41:40.856056: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-17 04:41:40.856705: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-17 04:41:40.856837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1734] Found device 0 with properties: 
pciBusID: 0000:19:00.0 name: Vega 20 [Radeon VII]     ROCm AMDGPU Arch: gfx906:sramecc-:xnack-
coreClock: 1.801GHz coreCount: 60 deviceMemorySize: 15.98GiB deviceMemoryBandwidth: 953.67GiB/s
2021-06-17 04:41:40.856860: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1734] Found device 1 with properties: 
pciBusID: 0000:b5:00.0 name: Vega 20 [Radeon VII]     ROCm AMDGPU Arch: gfx906:sramecc-:xnack-
coreClock: 1.801GHz coreCount: 60 deviceMemorySize: 15.98GiB deviceMemoryBandwidth: 953.67GiB/s
2021-06-17 04:41:40.856874: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocblas.so
2021-06-17 04:41:40.856881: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libMIOpen.so
2021-06-17 04:41:40.856889: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libhipfft.so
2021-06-17 04:41:40.856894: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocrand.so
2021-06-17 04:41:40.856938: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
2021-06-17 04:41:40.856953: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-17 04:41:40.856959: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 1 
2021-06-17 04:41:40.856965: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N N 
2021-06-17 04:41:40.856969: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 1:   N N 
2021-06-17 04:41:40.857041: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15385 MB memory) -> physical GPU (device: 0, name: Vega 20 [Radeon VII], pci bus id: 0000:19:00.0)
2021-06-17 04:41:41.118779: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15385 MB memory) -> physical GPU (device: 1, name: Vega 20 [Radeon VII], pci bus id: 0000:b5:00.0)
2021-06-17 04:41:41.381644: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-17 04:41:41.382234: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 3299990000 Hz

Function on GPU returns:  tf.Tensor(4.0, shape=(), dtype=float32)


2021-06-17 04:41:41.549669: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c96a15d5e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-06-17 04:41:41.549689: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-06-17 04:41:41.556128: I tensorflow/compiler/jit/xla_compilation_cache.cc:333] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

Function on CPU with XLA returns:  tf.Tensor(4.0, shape=(), dtype=float32)


2021-06-17 04:41:41.557188: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c96a0e4dd0 initialized for platform ROCM (this does not guarantee that XLA will be used). Devices:
2021-06-17 04:41:41.557203: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Vega 20 [Radeon VII], AMDGPU ISA version: gfx906:sramecc-:xnack-
2021-06-17 04:41:41.557209: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): Vega 20 [Radeon VII], AMDGPU ISA version: gfx906:sramecc-:xnack-
2021-06-17 04:41:41.561751: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at xla_ops.cc:238 : Internal: unable to find ld.lld in PATH: No such file or directory
Traceback (most recent call last):
  File "simple_function.py", line 33, in <module>
    vxla = simple_function_xla(2.)
  File "/home/robhicks/anaconda3/envs/tf-rocm-3.7/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/home/robhicks/anaconda3/envs/tf-rocm-3.7/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 862, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/robhicks/anaconda3/envs/tf-rocm-3.7/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2943, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access
  File "/home/robhicks/anaconda3/envs/tf-rocm-3.7/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1919, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/robhicks/anaconda3/envs/tf-rocm-3.7/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 560, in call
    ctx=ctx)
  File "/home/robhicks/anaconda3/envs/tf-rocm-3.7/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InternalError: unable to find ld.lld in PATH: No such file or directory [Op:__inference_simple_function_xla_11]
```

[rocminfo.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/6687935/rocminfo.txt)

**Comment by roblem** [comment]
Using amdgpu (downloaded from amd) with the latest docker image, runs without problems:  
```
Running in: /usr/bin/python
2021-06-21 17:11:40.397175: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libamdhip64.so
2021-06-21 17:11:40.474929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1747] Found device 0 with properties: 
pciBusID: 0000:19:00.0 name: Vega 20     ROCm AMDGPU Arch: gfx906:sramecc-:xnack-
coreClock: 1.801GHz coreCount: 60 deviceMemorySize: 15.98GiB deviceMemoryBandwidth: 953.67GiB/s
2021-06-21 17:11:40.474994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1747] Found device 1 with properties: 
pciBusID: 0000:b5:00.0 name: Vega 20     ROCm AMDGPU Arch: gfx906:sramecc-:xnack-
coreClock: 1.801GHz coreCount: 60 deviceMemorySize: 15.98GiB deviceMemoryBandwidth: 953.67GiB/s
2021-06-21 17:11:40.475124: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocblas.so
2021-06-21 17:11:40.476793: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libMIOpen.so
2021-06-21 17:11:40.495351: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libhipfft.so
2021-06-21 17:11:40.495604: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocrand.so
2021-06-21 17:11:40.495711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1
TF devices:  [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'), PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')]

2021-06-21 17:11:40.496593: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-21 17:11:40.497425: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1747] Found device 0 with properties: 
pciBusID: 0000:19:00.0 name: Vega 20     ROCm AMDGPU Arch: gfx906:sramecc-:xnack-
coreClock: 1.801GHz coreCount: 60 deviceMemorySize: 15.98GiB deviceMemoryBandwidth: 953.67GiB/s
2021-06-21 17:11:40.497458: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1747] Found device 1 with properties: 
pciBusID: 0000:b5:00.0 name: Vega 20     ROCm AMDGPU Arch: gfx906:sramecc-:xnack-
coreClock: 1.801GHz coreCount: 60 deviceMemorySize: 15.98GiB deviceMemoryBandwidth: 953.67GiB/s
2021-06-21 17:11:40.497473: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocblas.so
2021-06-21 17:11:40.497486: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libMIOpen.so
2021-06-21 17:11:40.497495: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libhipfft.so
2021-06-21 17:11:40.497506: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library librocrand.so
2021-06-21 17:11:40.497552: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1871] Adding visible gpu devices: 0, 1
2021-06-21 17:11:40.497569: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1258] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-06-21 17:11:40.497575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1264]      0 1 
2021-06-21 17:11:40.497580: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 0:   N N 
2021-06-21 17:11:40.497586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1277] 1:   N N 
2021-06-21 17:11:40.497671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15868 MB memory) -> physical GPU (device: 0, name: Vega 20, pci bus id: 0000:19:00.0)
2021-06-21 17:11:40.746731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1418] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 15868 MB memory) -> physical GPU (device: 1, name: Vega 20, pci bus id: 0000:b5:00.0)
2021-06-21 17:11:41.006145: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2021-06-21 17:11:41.006635: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 3299990000 Hz
2021-06-21 17:11:41.012576: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:507] ROCm Fusion is enabled.

Function on GPU returns:  tf.Tensor(4.0, shape=(), dtype=float32)


2021-06-21 17:11:41.181843: I tensorflow/compiler/xla/service/service.cc:169] XLA service 0x7fe4305841f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-06-21 17:11:41.181871: I tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): Host, Default Version
2021-06-21 17:11:41.188150: I tensorflow/compiler/jit/xla_compilation_cache.cc:337] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

Function on CPU with XLA returns:  tf.Tensor(4.0, shape=(), dtype=float32)


2021-06-21 17:11:41.189207: I tensorflow/compiler/xla/service/service.cc:169] XLA service 0x7fe43065e250 initialized for platform ROCM (this does not guarantee that XLA will be used). Devices:
2021-06-21 17:11:41.189228: I tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (0): Vega 20, AMDGPU ISA version: gfx906:sramecc-:xnack-
2021-06-21 17:11:41.189236: I tensorflow/compiler/xla/service/service.cc:177]   StreamExecutor device (1): Vega 20, AMDGPU ISA version: gfx906:sramecc-:xnack-

Function on GPU with XLA returns:  tf.Tensor(4.0, shape=(), dtype=float32)
```
Apparently, I haven't installed the rocm components correctly on my machine, and would appreciate some guidance on that.

**Comment by papadako** [comment]
Hi Rob,

I also had some problems with my Radeon VII which I resolved by upgrading
to the latest unstable 5.13 rc kernel.

**Comment by roblem** [comment]
This is very helpful.  So the process would go like this:
1. Delete all amdgpu drivers/kernel mods downloaded from amd
2. Delete all rocm packages 
3. Reboot
3. Upgrade the kernel to 5.13 (kinda scary given that I won't have physical access to the machine until Aug.)
4. Reboot
4. Install ROCm (without rocm-dkms)
5. Profit

**Comment by papadako** [comment]
In this case, I would avoid making such changes without physical access.

But yes the process would be what you have described

**Comment by roblem** [comment]
Yeah, for now I'll just use the docker image with the amd drivers.  Unless there is a way to fix the llvm issue.  Thanks again.
