### ISSUE TITLE
import tensorflow 2.4.3 ubuntu 20.02 Rocm 4.3 python 3.8

### ISSUE THREAD

**Issue by alexmondaini** [ROCmSoftwarePlatform/tensorflow-upstream#1415]
**System information**
- OS Platform and Distribution (Linux Ubuntu 20.04):
- TensorFlow installed from (binary):
- TensorFlow version:2.4.3
- Python version:3.8.10
- Installed using virtualenv? pip? conda?: pip, no virtualenv
- ROCm/MIOpen version:4.3.0.40300-52
- GPU model and memory: VGA 8GB ASRock Radeon RX 590

```
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: librccl.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/.local/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/alex/.local/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/alex/.local/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/alex/.local/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: librccl.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors
```

**Comment by sunway513** [comment]
Hi @alexmondaini , RX590 is not supported by ROCm, for details you can refer to the following thread:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/1230#issuecomment-789537799
cc @ROCmSupport
