### ISSUE TITLE
ROCm/tensorflow run_glue.py 

### ISSUE THREAD

**Issue by neqkir** [ROCmSoftwarePlatform/tensorflow-upstream#1450]
Hi,

using ROCm/tensorkflow in a docker image, I try to run the script run_glue.py, get the error below

I suspect a tf version problem, I am using

root@mi100:/root/models/official/nlp/finetuning/glue# python3 -c 'import tensorflow as tf; print(tf.__version__)'
2.6.0

I made sure tensorflow_text is installed

**Describe the current behavior**

root@mi100:/root/models/official/nlp/finetuning/glue# python3 run_glue.py
WARNING:absl:Encountered error when importing tensorflow_text: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
Traceback (most recent call last):
  File "run_glue.py", line 30, in <module>
    from official.common import registry_imports  # pylint: disable=unused-import
  File "/root/models/official/common/registry_imports.py", line 18, in <module>
    from official.nlp.configs import experiment_configs
  File "/root/models/official/nlp/configs/experiment_configs.py", line 19, in <module>
    from official.nlp.configs import wmt_transformer_experiments
  File "/root/models/official/nlp/configs/wmt_transformer_experiments.py", line 22, in <module>
    from official.nlp.data import wmt_dataloader
  File "/root/models/official/nlp/data/wmt_dataloader.py", line 38, in <module>
    import tensorflow_text as tftxt
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/__init__.py", line 21, in <module>
    from tensorflow_text.python import metrics
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/__init__.py", line 20, in <module>
    from tensorflow_text.python.metrics.text_similarity_metric_ops import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/text_similarity_metric_ops.py", line 28, in <module>
    gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so'))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

**Comment by sunway513** [comment]
Hi @neqkir , can you fill in the standard "bug report" questions using the following link?
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/new?assignees=&labels=type%3Abug&template=00-bug-issue.md

**Comment by ppanchad-amd** [comment]
Hi @neqkir. Apologies for the lack of response. Do you still need assistance with this ticket? Thanks!

**Comment by tcgu-amd** [comment]
@neqkir, the issue is no longer observed on our end on the latest ROCm version. I will be closing this issue for now. Please feel free to continue to follow up if further assistance is required. Thanks!
