### ISSUE TITLE
error raised in tensorflow_addons when running bert run_classifier.py

### ISSUE THREAD

**Issue by neqkir** [ROCmSoftwarePlatform/tensorflow-upstream#1451]
Hi,

using ROCm/tensorkflow in a docker image, I try to run the script run_classifier.py, get the error below

root@mi100:/root/models/official/nlp/finetuning/glue# python3 -c 'import tensorflow as tf; print(tf.version)'
2.6.0

root@mi100:/root/models/official/nlp/bert# python3 run_classifier.py   --mode='train_and_eval'   --input_meta_data_path=${GLUE_DIR}/${TASK}_meta_data   --train_data_path=${GLUE_DIR}/${TASK}_train.tf_record   --eval_data_path=${GLUE_DIR}/${TASK}_eval.tf_record   --bert_config_file=${BERT_BASE_DIR}/bert_config.json   --init_checkpoint=${BERT_BASE_DIR}/bert_model.ckpt   --train_batch_size=4   --eval_batch_size=4   --steps_per_loop=1   --learning_rate=2e-5   --num_train_epochs=3   --model_dir=${MODEL_DIR}   --distribution_strategy=mirrored

Traceback (most recent call last):
  File "run_classifier.py", line 30, in <module>
    from official.nlp import optimization
  File "/root/models/official/nlp/optimization.py", line 22, in <module>
    import tensorflow_addons.optimizers as tfa_optimizers
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_addons/__init__.py", line 18, in <module>
    _check_tf_version()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_addons/utils/ensure_tf_install.py", line 36, in _check_tf_version
    if "dev" in tf.__version__:
AttributeError: module 'tensorflow' has no attribute '__version__'

**Comment by tcgu-amd** [comment]
Hi @neqkir sorry for the lack of replies. Since this issue does not seem to occur in the latest version of Tensorflow + ROCm, I will be closing this issue for now. Thanks!
