### ISSUE TITLE
NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

### ISSUE THREAD

**Issue by neqkir** [ROCmSoftwarePlatform/tensorflow-upstream#1455]
Tensorflow 2.6.0 in a docker session

Code runs well in a local environment with "native" Tensorflow same version, encounters this error when run on a server with a docker session containing a tensorflow-rocm image

tensorflow_text has been installed 

```
root@mymachine:/root/rnn/# python3 rnn_002.py
Traceback (most recent call last):
  File "rnn_002.py", line 18, in <module>
    import tensorflow_text as tf_text
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/__init__.py", line 21, in <module>
    from tensorflow_text.python import metrics
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/__init__.py", line 20, in <module>
    from tensorflow_text.python.metrics.text_similarity_metric_ops import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/text_similarity_metric_ops.py", line 28, in <module>
    gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.so'))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
```

**Comment by neqkir** [comment]
Seems to be related to Tensorflow versions and GPU support, https://stackoverflow.com/questions/67690805/tensorflow-text-disables-gpu-on-colab

Would like to run everything in a cohesive manner with the latest Tensorflow 2.6.0 though

**Comment by ppanchad-amd** [comment]
Hi @neqkir. Apologies for the lack of response on this ticket.  Do you still need assistance with this ticket? If not, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@neqkir. Closing ticket. Please re-open if you still need assistance with this ticket. Thanks!
