### ISSUE TITLE
Error with masking

### ISSUE THREAD

**Issue by ianzur** [ROCmSoftwarePlatform/tensorflow-upstream#1460]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution: Linux Debian bullseye
- ROCm stack installed via `apt`: v4.3.0
- TensorFlow installed from: source
- TensorFlow version: 2.7.0
- Python version: 3.9.2
- Bazel version: 4.2.1
- GCC/Compiler version: 10.2.1 20210110
- CUDA/cuDNN version: ? AMD platform
- GPU model and memory: gfx900, Vega 10 XTX, 16GB
- `merge-210831-4-g693771b42d5 2.7.0`

**Describe the current behavior**
Passing mask to RNN layer raises framework invalid argument error.

**Describe the expected behavior**
masking should be supported.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): Maybe if given direction
- Briefly describe your candidate solution(if contributing): Not sure where(what) causes this error 

**Standalone code to reproduce the issue**
```
import numpy as np
import tensorflow as tf


def fake_ragged_data():
    """create fake ragged data, return concatenated data and row splits"""

    examples = []
    examples.append(np.random.rand(4, 3))
    examples.append(np.random.rand(3, 3))
    examples.append(np.random.rand(5, 3))
    examples.append(np.random.rand(2, 3))

    row_splits = [0]
    for i, example in enumerate(examples):
      row_splits.append(example.shape[0] + row_splits[i])

    return np.concatenate(examples).astype(np.float32) * 10, row_splits
  

if __name__ == "__main__":

    ragged_data, row_splits = fake_ragged_data()
    
    # In my real data zeros exist, so I pad and mask with another value
    mask_value = 99

    x = tf.RaggedTensor.tf.RaggedTensor.from_row_splits(ragged_data, row_splits).to_tensor(
        default_value=mask_value, shape=(None, 5, 3)
    )
    # print(x[0])

    # create model (no need to compile, I am not training in this example)
    model = tf.keras.Sequential()
    model.add(tf.keras.layers.Masking(mask_value))
    model.add(tf.keras.layers.GRU(6))
    # model.add(tf.keras.layers.LSTM(6)) # LSTM (instead of GRU) also results in the same error.


    model(x)
```

**Error + Traceback**
```
2021-10-04 14:34:01.132049: W tensorflow/core/framework/op_kernel.cc:1694] OP_REQUIRES failed at cudnn_rnn_ops.cc:1552 : INVALID_ARGUMENT: ROCm MIOpen only supports packed input output.
Traceback (most recent call last):
  File ".../test_rocm_masking.py", line 39, in <module>
    model(x)
  File ".../.env/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File ".../.env/lib/python3.9/site-packages/keras/engine/sequential.py", line 369, in call
    return super(Sequential, self).call(inputs, training=training, mask=mask)
  File ".../.env/lib/python3.9/site-packages/keras/engine/functional.py", line 414, in call
    return self._run_internal_graph(
  File ".../.env/lib/python3.9/site-packages/keras/engine/functional.py", line 550, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File ".../.env/lib/python3.9/site-packages/keras/layers/recurrent.py", line 659, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File ".../.env/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File ".../.env/lib/python3.9/site-packages/keras/layers/recurrent_v2.py", line 443, in call
    last_output, outputs, runtime, states = self._defun_gru_call(
  File ".../.env/lib/python3.9/site-packages/keras/layers/recurrent_v2.py", line 515, in _defun_gru_call
    last_output, outputs, new_h, runtime = gpu_gru(**gpu_gru_kwargs)
  File ".../.env/lib/python3.9/site-packages/keras/layers/recurrent_v2.py", line 659, in gpu_gru
    outputs, h, _, _, _ = tf.raw_ops.CudnnRNNV3(
  File ".../.env/lib/python3.9/site-packages/tensorflow/python/util/tf_export.py", line 404, in wrapper
    return f(**kwargs)
  File ".../.env/lib/python3.9/site-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py", line 1905, in cudnn_rnnv3
    return cudnn_rnnv3_eager_fallback(
  File ".../.env/lib/python3.9/site-packages/tensorflow/python/ops/gen_cudnn_rnn_ops.py", line 2002, in cudnn_rnnv3_eager_fallback
    _result = _execute.execute(b"CudnnRNNV3", 5, inputs=_inputs_flat,
  File ".../.env/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 58, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: ROCm MIOpen only supports packed input output. [Op:CudnnRNNV3]
```

Moved issue from [MIOpen #1203](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1203). 
@deven-amd @reza-amd

**Comment by ianzur** [comment]
I looked through the test cases and found that this is expected behavior. ROCm MIOpen currently does not support masking. Closing this issue, re-opening MIOpen Issue as feature request.

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/7e8f960bb398526aea7e045884101029fd21bddd/tensorflow/python/keras/layers/gru_v2_test.py#L149
