### ISSUE TITLE
Can't compile tensorflow from source with rocm 4.5.2

### ISSUE THREAD

**Issue by Miskinis** [ROCmSoftwarePlatform/tensorflow-upstream#1520]
**System information**
- OS Platform and Distribution (Ubuntu 20.04.3):
- Python version: 3.8
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 9.3
- ROCm/MIOpen version: 4.5.2
- GPU model and memory: gfx 900, Vega 56, 8 GB

**Describe the problem**
Unable to compile tensorflow from source no matter what version I pick. The installation seems to look for a file that does not exists in rocm-4.5.2 "rocm_agent_enumerator".
The rocm installation itself seems to be fine, done it using `sudo amdgpu-install --usecase=hiplibsdk,rocm` and got no errors.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
git clone -b r2.7-rocm-enhanced https://github.com/ROCmSoftwarePlatform/tensorflow-upstream.git
cd tensorflow-upstream
./build_rocm_python3

```
**Any other info / logs**
```
You have bazel 3.7.2 installed.
Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.8/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]
Do you wish to build TensorFlow with CUDA support? [y/N]: No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]: 

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=mkl_aarch64 	# Build with oneDNN and Compute Library for the Arm Architecture (ACL).
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v1          	# Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=nogcp       	# Disable GCP support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [rocm]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/eimantas/tensorflow-upstream/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/eimantas/tensorflow-upstream/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from /home/eimantas/tensorflow-upstream/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3 --config=rocm --action_env ROCM_PATH=/opt/rocm-4.5.2 --action_env ROCBLAS_TENSILE_LIBPATH=/opt/rocm-4.5.2/lib/library
INFO: Reading rc options for 'build' from /home/eimantas/tensorflow-upstream/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /home/eimantas/tensorflow-upstream/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/eimantas/tensorflow-upstream/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:rocm in file /home/eimantas/tensorflow-upstream/.bazelrc: --crosstool_top=@local_config_rocm//crosstool:toolchain --define=using_rocm_hipcc=true --repo_env TF_NEED_ROCM=1
INFO: Found applicable config definition build:opt in file /home/eimantas/tensorflow-upstream/.tf_configure.bazelrc: --copt=-Wno-sign-compare --host_copt=-Wno-sign-compare
INFO: Found applicable config definition build:rocm in file /home/eimantas/tensorflow-upstream/.bazelrc: --crosstool_top=@local_config_rocm//crosstool:toolchain --define=using_rocm_hipcc=true --repo_env TF_NEED_ROCM=1
INFO: Found applicable config definition build:linux in file /home/eimantas/tensorflow-upstream/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/eimantas/tensorflow-upstream/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Repository local_config_rocm instantiated at:
  /home/eimantas/tensorflow-upstream/WORKSPACE:15:14: in <toplevel>
  /home/eimantas/tensorflow-upstream/tensorflow/workspace2.bzl:1079:19: in workspace
  /home/eimantas/tensorflow-upstream/tensorflow/workspace2.bzl:100:19: in _tf_toolchains
Repository rule rocm_configure defined at:
  /home/eimantas/tensorflow-upstream/third_party/gpus/rocm_configure.bzl:859:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_rocm':
   Traceback (most recent call last):
	File "/home/eimantas/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 840, column 38, in _rocm_autoconf_impl
		_create_local_rocm_repository(repository_ctx)
	File "/home/eimantas/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 544, column 35, in _create_local_rocm_repository
		rocm_config = _get_rocm_config(repository_ctx, bash_bin, find_rocm_config_script)
	File "/home/eimantas/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 400, column 41, in _get_rocm_config
		amdgpu_targets = _amdgpu_targets(repository_ctx, rocm_toolkit_path, bash_bin),
	File "/home/eimantas/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 216, column 25, in _amdgpu_targets
		result = execute(repository_ctx, [bash_bin, "-c", cmd])
	File "/home/eimantas/tensorflow-upstream/third_party/remote_config/common.bzl", line 230, column 13, in execute
		fail(
Error in fail: Repository command failed
/usr/bin/bash: /opt/rocm-4.5.2/bin/rocm_agent_enumerator: No such file or directory
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_rocm//rocm': Repository command failed
/usr/bin/bash: /opt/rocm-4.5.2/bin/rocm_agent_enumerator: No such file or directory
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_rocm//rocm': Repository command failed
/usr/bin/bash: /opt/rocm-4.5.2/bin/rocm_agent_enumerator: No such file or directory
INFO: Elapsed time: 2.974s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

```

**Comment by Miskinis** [comment]
After some very deep, manual cleaning and reinstalling, everything seems to work now. The uninstall guides for 4.5 and below seems to be inaccurate, cause I had leftover packages that somehow messed with the installations. Also why did installation never report an error that something was incompatible and something failed to install?
`apt list --installed | grep -i roc` helped here a bit.
