### ISSUE TITLE
TensorFlow Probability

### ISSUE THREAD

**Issue by chriselrod** [ROCmSoftwarePlatform/tensorflow-upstream#210]
For GPU support:
https://www.tensorflow.org/probability/install
> `pip install --upgrade tensorflow-probability-gpu  # depends on tensorflow-gpu`
>
> Currently, TensorFlow Probability does not contain any GPU-specific code. The primary difference between these packages is that tensorflow-probability-gpu depends on a GPU-enabled version of TensorFlow.

Now, because tensorflow-probability-gpu does not actually contain any GPU-specific code, but merely depends on tensorflow-gpu, I imagine it should be easy to swap out back-ends, and depend on tensorflow-rocm instead.
Similar would apply to other libraries built on top of tensorflow-gpu.

Is there an easy way to swap out these tensorflow backends, or could we get a tensorflow-probability-rocm?
Should I file an issue at tensorflow-probability instead?

**Comment by whchung** [comment]
@parallelo could you help weigh in here? IIRC there was another package with similar dependency to `tensorflow-gpu` and there was a solution to that.

**Comment by parallelo** [comment]
Sure, let me dig those details up again.  Stay tuned.

**Comment by parallelo** [comment]
Have you tried the `--no-deps` flag for pip when installing `tensorflow-probability-gpu`?  If you go this route, you may need to install all of the other dependencies by hand.  

Alternatively, you could try this type of workflow:  
1) install both `tensorflow-probability-gpu` and `tensorflow-gpu` -- now you'll have all of the dependencies
2) uninstall `tensorflow-gpu` -- this should still leave the other probability-related dependencies intact
3) install `tensorflow-rocm`

Let us know if these suggestions work for you.  

Looking long-term, we'll have to request new target whl support from the `tensorflow/probability` maintainers (and for other similar projects).

**Comment by pricebenjamin** [comment]
The `tensorflow-rocm` dependencies appear to be sufficient for using `tensorflow-probability-gpu`.

```
pip install tensorflow-rocm
pip install tensorflow-probability-gpu --no-deps
```

I was able to run the first graph found in [Chapter 1](https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/blob/master/Chapter1_Introduction/Ch1_Introduction_TFP.ipynb) of [_Bayesian Methods for Hackers_](https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers) without issue.

**Comment by wrightpt** [comment]
thanks. I am trying to run the following:

```
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)
```

I get the following from my pycharm IDE:

```
/usr/bin/python3.5 /home/c/.PyCharmCE2018.2/config/scratches/scratch.py
Traceback (most recent call last):
  File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libhiprand.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/c/.PyCharmCE2018.2/config/scratches/scratch.py", line 1, in <module>
    import tensorflow as tf
  File "/home/c/.local/lib/python3.5/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/c/.local/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libhiprand.so.1: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Process finished with exit code 1
```

**Comment by wrightpt** [comment]
it may run if i use sudo from the command line. one second

**Comment by Chern2** [comment]
I try to install  tensorflow-probability-gpu following the advice from @pricebenjamin but  it seems to miss a module:
  File "/home/sychern/桌面/test/ops.py", line 2, in <module>
    import tensorflow_probability
  File "/home/sychern/.local/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 21, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/home/sychern/.local/lib/python3.6/site-packages/tensorflow_probability/python/__init__.py", line 22, in <module>
    from tensorflow_probability.python import distributions
  File "/home/sychern/.local/lib/python3.6/site-packages/tensorflow_probability/python/distributions/__init__.py", line 77, in <module>
    from tensorflow_probability.python.distributions.vector_diffeomixture import quadrature_scheme_softmaxnormal_gauss_hermite
  File "/home/sychern/.local/lib/python3.6/site-packages/tensorflow_probability/python/distributions/vector_diffeomixture.py", line 28, in <module>
    from tensorflow.contrib.linalg.python.ops import linear_operator_addition as linop_add_lib
ModuleNotFoundError: No module named 'tensorflow.contrib.linalg'

**Comment by pricebenjamin** [comment]
> ModuleNotFoundError: No module named 'tensorflow.contrib.linalg'

This is because `tf.contrib.linalg` was moved to `tf.linalg` in TensorFlow 1.12 ([release notes](https://github.com/tensorflow/tensorflow/releases/tag/v1.12.0)). Scroll through the [TF Probabiilty releases page](https://github.com/tensorflow/probability/releases) to determine which release corresponds to your version of TensorFlow. For example (from the releases page),

> This is the 0.5.0 release of TensorFlow Probability. It's tested and stable against TensorFlow 1.12.

Also, according to the [installation section](https://github.com/tensorflow/probability#installation) from their README, they no longer include `tensorflow` as a dependency for their package, meaning it's a bit easier to install:

```bash
# Assuming tensorflow-rocm==1.12.0 has already been installed...
pip install tensorflow-probability==0.5.0
```
