### ISSUE TITLE
iGPU causing issues with compilation.

### ISSUE THREAD

**Issue by briansp2020** [ROCmSoftwarePlatform/tensorflow-upstream#2292]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14

### Custom code

No

### OS platform and distribution

Linux Ubuntu 22.04 Server

### Python version

3.10

### Bazel version

6.1.0

### GPU model and memory

gfx1100 & gfx1032

### Current behavior?

When I compile r2.14-rocm-enhanced branch, depending on whether the iGPU is enabled or not, it seems to produce a different output. If I disable the iGPU when building tensorflow, everything works as expected. If I build with the iGPU enabled, I get the following error when running new-ai-benchmark. Does the build process detect the GPUs in the system and use that information to produce different output? I'm just using build_rocm_python3 script. Is it not what's used to build the whl package for distribution?

### Standalone code to reproduce the issue

```shell
Just build the same source code with the iGPU enabled and disabled.
```

### Relevant log output

```shell
(tf) root@rocm:~/tmp# python benchmark.py
2023-11-05 01:42:47.001980: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-05 01:42:47.022108: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-05 01:42:48.387035: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:48.395473: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:48.395500: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
>>   AI-Benchmark - 0.1.3.cm
>>   Let the AI Games begin
2023-11-05 01:42:49.487059: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.487110: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.487126: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.487190: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.487213: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.487232: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.487243: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1886] Created device /device:GPU:0 with 24024 MB memory:  -> device: 0, name: Radeon RX 7900 XTX, pci bus id: 0000:03:00.0
2023-11-05 01:42:49.623609: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.623669: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.623684: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.623711: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.623727: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.623735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1886] Created device /device:GPU:0 with 24024 MB memory:  -> device: 0, name: Radeon RX 7900 XTX, pci bus id: 0000:03:00.0
2023-11-05 01:42:49.623766: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.623786: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.623799: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.623818: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.623832: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:49.623838: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1886] Created device /device:GPU:0 with 24024 MB memory:  -> device: 0, name: Radeon RX 7900 XTX, pci bus id: 0000:03:00.0
*  TF Version: 2.14.0
*  Platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.35
*  CPU: AMD Ryzen 9 7900X 12-Core Processor
*  CPU RAM: 62 GB
*  GPU/0: Radeon RX 7900 XTX
*  GPU RAM: 23.5 GB
*  CUDA Version: N/A
*  CUDA Build: N/A
The benchmark is running...
The tests might take up to 20 minutes
Please don't interrupt the script

1/19. MobileNet-V2

2023-11-05 01:42:50.860383: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:50.860468: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:50.860503: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:50.860561: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:50.860596: I tensorflow/compiler/xla/stream_executor/rocm/rocm_gpu_executor.cc:756] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-11-05 01:42:50.860616: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1886] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 24024 MB memory:  -> device: 0, name: Radeon RX 7900 XTX, pci bus id: 0000:03:00.0
2023-11-05 01:42:50.970363: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:382] MLIR V1 optimization pass is not enabled
2023-11-05 01:42:51.127972: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:508] ROCm Fusion is enabled.
2023-11-05 01:42:51.580515: I tensorflow/core/common_runtime/gpu_fusion_pass.cc:508] ROCm Fusion is enabled.
2023-11-05 01:42:51.587953: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:30] 'hipModuleLoadData(&module, data)' failed with 'hipErrorNoBinaryForGpu'

2023-11-05 01:42:51.587983: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:30] 'hipModuleGetFunction(&function, module, kernel_name)' failed with 'hipErrorInvalidHandle'

2023-11-05 01:42:51.587992: W tensorflow/core/framework/op_kernel.cc:1827] INTERNAL: 'hipModuleLaunchKernel( function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<hipStream_t>(stream), params, nullptr)' failed with 'hipErrorInvalidHandle'
2023-11-05 01:42:51.588012: I tensorflow/core/framework/local_rendezvous.cc:421] Local rendezvous recv item cancelled. Key hash: 6084052615700386762
2023-11-05 01:42:51.593477: W tensorflow/compiler/mlir/tools/kernel_gen/tf_gpu_runtime_wrappers.cc:30] 'hipModuleUnload(it.second)' failed with 'hipErrorInvalidHandle'

Traceback (most recent call last):
  File "/root/tf/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1402, in _do_call
    return fn(*args)
  File "/root/tf/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1385, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/root/tf/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1478, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) INTERNAL: 'hipModuleLaunchKernel( function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<hipStream_t>(stream), params, nullptr)' failed with 'hipErrorInvalidHandle'
         [[{{node Mul}}]]
         [[output/_3]]
  (1) INTERNAL: 'hipModuleLaunchKernel( function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<hipStream_t>(stream), params, nullptr)' failed with 'hipErrorInvalidHandle'
         [[{{node Mul}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/tmp/benchmark.py", line 11, in <module>
    results = benchmark.run()
  File "/root/tf/lib/python3.10/site-packages/ai_benchmark/core.py", line 57, in run
    return utils.run_tests(
  File "/root/tf/lib/python3.10/site-packages/ai_benchmark/utils.py", line 547, in run_tests
    sess.run(output_, feed_dict={input_: data})
  File "/root/tf/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 972, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/root/tf/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1215, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/root/tf/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1395, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/root/tf/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1421, in _do_call
    raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node 'Mul' defined at (most recent call last):
Node: 'Mul'
Detected at node 'Mul' defined at (most recent call last):
Node: 'Mul'
2 root error(s) found.
  (0) INTERNAL: 'hipModuleLaunchKernel( function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<hipStream_t>(stream), params, nullptr)' failed with 'hipErrorInvalidHandle'
         [[{{node Mul}}]]
         [[output/_3]]
  (1) INTERNAL: 'hipModuleLaunchKernel( function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<hipStream_t>(stream), params, nullptr)' failed with 'hipErrorInvalidHandle'
         [[{{node Mul}}]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'Mul':

(tf) root@rocm:~/tmp#
```

**Comment by schung-amd** [comment]
Hi @briansp2020, you should disable the integrated graphics; see https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/prerequisites.html#disable-integrated-graphics-igp-if-applicable. With the iGPU enabled, ROCm is trying to use it and failing to do so as it is not supported.

You can try hiding the integrated graphics by setting HIP_VISIBLE_DEVICES to only your discrete GPU, but in general the integrated graphics should be disabled for ROCm to function properly. If you need additional guidance or this does not resolve your issue, feel free to comment and we can reopen.
