### ISSUE TITLE
build failed with Python3.11 ROCM6.1.0 BAZEL 7.1.1n gfx1100

### ISSUE THREAD

**Issue by gitleibin** [ROCmSoftwarePlatform/tensorflow-upstream#2531]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

v2.14.0-4248-g3448956e87e 2.14.0.600

### Custom code

Yes

### Python version

3.11

### Bazel version

7.1.1

### Current behavior?

```
  hdrs = glob([
        "rocm/include/hipcub/**",
        "rocm/include/rocprim/**",
    ]),
```

for these code I had modify it as  rocm/include/hipcub/*.*  rocm/include/hipcub/*.hpp
but it doesn't work 
How to set the   --incompatible_disallow_empty_glob with blaze
```
INFO: Found applicable config definition build:linux in file /home/xxxxx/.bazelrc: --cxxopt=-std=c++17 --host_cxxopt=-std=c++17
WARNING: The following configs were expanded more than once: [rocm, rocm_base, no_tfrt, release_cpu_linux_base]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
ERROR: Traceback (most recent call last):
	File "/home/xxxxx/.cache/bazel/_bazel_leibin/7483686ba524c14c314b63f52f079dca/external/local_config_rocm/rocm/BUILD", line 132, column 16, in <toplevel>
		hdrs = glob([
Error in glob: glob pattern 'rocm/include/hipcub/**' didn't match anything, but allow_empty is set to False (the default value of allow_empty can be set with --incompatible_disallow_empty_glob).
ERROR: /home/xxxxxx/gitRepo/tensorflow-upstream/tensorflow/BUILD:1177:21: errors encountered resolving select() keys for //tensorflow:libtensorflow_framework.so.2.17.0
ERROR: Analysis of target '//tensorflow/tools/pip_package:wheel' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.071s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
FAILED: 
    Fetching repository @@flatbuffers; starting
    Fetching repository @@snappy; starting
    Fetching repository @@absl_py; starting
    Fetching repository @@com_google_absl; starting
    Fetching https://storage.googleapis.com/.../google/snappy/archive/984b191f0fefdeb17050b42a90b7625999c13b8d.tar.gz; Checking in SHA-256 cache

```

### Standalone code to reproduce the issue

```shell
Error in glob: glob pattern 'rocm/include/hipcub/**' didn't match anything, but allow_empty is set to False (the default value of allow_empty can be set with --incompatible_disallow_empty_glob).

ERROR: /home/xxxxxx/gitRepo/tensorflow-upstream/tensorflow/BUILD:1177:21: errors encountered resolving select() keys for //tensorflow:libtensorflow_framework.so.2.17.0
```

### Relevant log output

```shell
d twice and may lead to unexpected behavior.
ERROR: Traceback (most recent call last):
	File "/home/leibin/.cache/bazel/_bazel_leibin/7483686ba524c14c314b63f52f079dca/external/local_config_rocm/rocm/BUILD", line 132, column 16, in <toplevel>
		hdrs = glob([
Error in glob: glob pattern 'rocm/include/hipcub/*.hpp' didn't match anything, but allow_empty is set to False (the default value of allow_empty can be set with --incompatible_disallow_empty_glob).
ERROR: /home/leibin/gitRepo/tensorflow-upstream/tensorflow/BUILD:1177:21: errors encountered resolving select() keys for //tensorflow:libtensorflow_framework.so.2.17.0
ERROR: Analysis of target '//tensorflow/tools/pip_package:wheel' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.071s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
FAILED: 
    Fetching repository @@flatbuffers; starting
    Fetching repository @@snappy; starting
    Fetching repository @@absl_py; starting
    Fetching repository @@com_google_absl; starting
    Fetching https://storage.googleapis.com/.../google/snappy/archive/984b191f0fefdeb17050b42a90b7625999c13b8d.tar.gz; Checking in SHA-256 cache
```

**Comment by tcgu-amd** [comment]
Hi @gitleibin sorry for the lack of responses. For your problem,
```
  hdrs = glob([
        "/opt/rocm/include/hipcub/*",
        "/opt/rocm/include/rocprim/*",
])
```
might work better. 
If the problem still persists, try our latest build with ROCm 6.2.4 and BAZEL 6.5.0. The build should work on Ubuntu 22.04 with gfx1100.

Thanks!

**Comment by tcgu-amd** [comment]
Hi, this issue will be closed for now due to inactivity. However, please feel free to ask follow up questions. Thanks!
