### ISSUE TITLE
failed to memset memory: HIP_ERROR_InvalidValue

### ISSUE THREAD

**Issue by AndreasGocht** [ROCmSoftwarePlatform/tensorflow-upstream#277]
Hey there,

in short, I am not able to run a minimal TensorFlow example. TF fails with:
```
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to memcopy into scratch buffer for device 0
         [[{{node _SOURCE}} = NoOp[]()]]
```
But there is an error before:
```
2019-01-03 22:03:00.418217: E tensorflow/stream_executor/rocm/rocm_driver.cc:461] failed to memset memory: HIP_ERROR_InvalidValue
```
To me this seems to be a problem with the ROCm software stack, but to be honest I have no Idea :wink: .

I tried to collect all relevant details below.

Best,

Andreas

### System Settings
I tried to use ROCm TensorFlow using my AMD APU (Ryzen 2400G).
I am running Debian Testing. My current Kernel version is:
```
Linux 4.19.0-1-amd64 #1 SMP Debian 4.19.12-1 (2018-12-22) x86_64 GNU/Linux
```
I installed the ROCm stack from the repository:
```
deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main
```
And the package
```
sudo apt install rocm-dev
```
I Installed TensorFlow using pip, e.g. 
```
pip install tensorflow-rocm
```
Python is python3.6, and I do not have any additional graphic cards installed. I am using a virtual environment.

### Issue
I tried to run a basic tensorflow example (https://www.tensorflow.org/tutorials/):
```
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)
```
When doing so the training fails with the following error messages:
```
WARNING:tensorflow:From /home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/ops/distributions/distribution.py:265: ReparameterizationType.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From /home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/ops/distributions/bernoulli.py:169: RegisterKL.__init__ (from tensorflow.python.ops.distributions.kullback_leibler) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Epoch 1/5
2019-01-03 22:02:56.256900: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-01-03 22:02:56.257690: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1530] Found device 0 with properties: 
name: AMD Ryzen 5 2400G with Radeon Vega Graphics
AMDGPU ISA: gfx902
memoryClockRate (GHz) 1.25
pciBusID 0000:38:00.0
Total memory: 16.00GiB
Free memory: 15.75GiB
2019-01-03 22:02:56.257713: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Adding visible gpu devices: 0
2019-01-03 22:02:56.257727: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1051] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-03 22:02:56.257733: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1057]      0 
2019-01-03 22:02:56.257739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1070] 0:   N 
2019-01-03 22:02:56.257771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15321 MB memory) -> physical GPU (device: 0, name: AMD Ryzen 5 2400G with Radeon Vega Graphics, pci bus id: 0000:38:00.0)
2019-01-03 22:03:00.418217: E tensorflow/stream_executor/rocm/rocm_driver.cc:461] failed to memset memory: HIP_ERROR_InvalidValue
Traceback (most recent call last):
  File "/home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to memcopy into scratch buffer for device 0
         [[{{node _SOURCE}} = NoOp[]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 17, in <module>
    model.fit(x_train, y_train, epochs=5)
  File "/home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1645, in fit
    validation_steps=validation_steps)
  File "/home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 215, in fit_loop
    outs = f(ins_batch)
  File "/home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2950, in __call__
    session = get_session()
  File "/home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 469, in get_session
    _initialize_variables(session)
  File "/home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 732, in _initialize_variables
    [variables_module.is_variable_initialized(v) for v in candidate_vars])
  File "/home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/andreas/virtenv/a/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to memcopy into scratch buffer for device 0
         [[{{node _SOURCE}} = NoOp[]()]]
```

**Comment by parallelo** [comment]
Hi Andreas.  Our APUs are currently not supported by various components in the ROCm stack.  Details on hardware support can be found here:  https://github.com/RadeonOpenCompute/ROCm#supported-gpus

**Comment by AndreasGocht** [comment]
Alright, but shouldt the implementation than fall back to the traditional tensorflow CPU implementation, as tensorflow-gpu does, when no graphic card is available?

Best,

Andreas

**Comment by AndreasGocht** [comment]
> * use a ROCm-supported discrete GPU + CPU combo via the tensorflow-rocm pip package

To do so, I have to get my finges on an AMD Graphics card. I am not sure, if this is going to happen anytime soon.

> * or if using the CPU is suitable for your particular workload, use the official CPU-only tensorflow pip package

I have to figure out if this is sufficient. As I understand there is nothing similar to Intels MKL to speed up the computation on AMD CPUS?

> Thanks for reporting the issue. We'll take a look at the fall-back code.

Thank you, for your work 😄.

Best,

Andreas

**Comment by parallelo** [comment]
Hi Andreas, 

> I have to figure out if this is sufficient. As I understand there is nothing similar to Intels MKL to speed up the computation on AMD CPUS?

You can find a partial list of AMD maintained CPU-targeted numerical libs here:  https://developer.amd.com/amd-cpu-libraries/ .  

I've read that MKL-DNN also works on modern AMD CPUs (i.e. x86-64 w/ AVX).  However, my focus has been on GPUs, so I don't have 1st-hand experience with that.

I'll close this ticket for now, but please feel free to re-open this ticket and/or create a new ticket in the future.

**Comment by AndreasGocht** [comment]
Thanks.
