### ISSUE TITLE
Simple RCCL all_sum test script triggers `Memory access fault by GPU node-1`

### ISSUE THREAD

**Issue by syoyo** [ROCmSoftwarePlatform/tensorflow-upstream#369]
**System information**
- Have I written custom code: No
- OS Platform and Distribution: Ubuntu 18.04.2
- TensorFlow installed from: binary(`pip install tensorflow-rocm`)
- TensorFlow version: 1.13.1
- Python version: 3.6
- ROCm/MIOpen version: 2.2 + 1.7.1
- GPU model and memory: VEGA 64 x 2

**Describe the current behavior**

A simple test script using `rccl.all_sum`(or other RCCL ops?) causes segmentation fault.
A tensor is assigned to each GPU device, then use `all_sum` to compute a sum with collective operation.

**Describe the expected behavior**

I think it should run without segmentation fault.

Here is an equivalent code in NCCL.
At least I have confirmed this NCCL version of script works well on NVIDIA platform(1080 Ti + 1070. CUDA 10 + TensorFlow 1.13.1).

```
import tensorflow as tf

from tensorflow.python.ops import nccl_ops
import numpy as np

def network(x):
    with tf.device('/gpu:1'):
        x1= tf.reshape(x, [-1, 4, 4])
    with tf.device('/gpu:0'):
        x0= tf.reshape(x, [-1, 4, 4])
        x0 = nccl_ops.all_sum([x0,x1])
        result = tf.identity(x0)
        return result

x = np.random.ranf(size=[2, 4, 4])
y_pre = network(x)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    ret = sess.run(y_pre)
    print(ret)
```

**Code to reproduce the issue**

```
import tensorflow as tf

import tensorflow.contrib.rccl as rccl
import numpy as np

def network(x):
    with tf.device('/gpu:1'):
        x1= tf.reshape(x, [-1, 4, 4])
    with tf.device('/gpu:0'):
        x0= tf.reshape(x, [-1, 4, 4])
        x0 = rccl.all_sum([x0,x1])
        result = tf.identity(x0)
        return result

x = np.random.ranf(size=[2, 4, 4])
y_pre = network(x)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    ret = sess.run(y_pre)
    print(ret)
```

**Other info / logs**

```
$ python test.py 
2019-03-24 17:02:21.063273: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-03-24 17:02:21.070210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1531] Found device 0 with properties: 
name: Vega 10 XT [Radeon RX Vega 64]
AMDGPU ISA: gfx900
memoryClockRate (GHz) 1.59
pciBusID 0000:28:00.0
Total memory: 7.98GiB
Free memory: 7.73GiB
2019-03-24 17:02:21.070517: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1531] Found device 1 with properties: 
name: Vega 10 XT [Radeon RX Vega 64]
AMDGPU ISA: gfx900
memoryClockRate (GHz) 1.59
pciBusID 0000:2b:00.0
Total memory: 7.98GiB
Free memory: 7.73GiB
2019-03-24 17:02:21.071182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1642] Adding visible gpu devices: 0, 1
2019-03-24 17:02:21.071344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-24 17:02:21.071358: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1059]      0 1 
2019-03-24 17:02:21.071365: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1072] 0:   N N 
2019-03-24 17:02:21.071370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1072] 1:   N N 
2019-03-24 17:02:21.071475: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7524 MB memory) -> physical GPU (device: 0, name: Vega 10 XT [Radeon RX Vega 64], pci bus id: 0000:28:00.0)
2019-03-24 17:02:21.144138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 7524 MB memory) -> physical GPU (device: 1, name: Vega 10 XT [Radeon RX Vega 64], pci bus id: 0000:2b:00.0)
Memory access fault by GPU node-1 (Agent handle: 0x5565e0e43340) on address 0x7fc29f400000. Reason: Page not present or supervisor privilege.
Aborted (core dumped)
```

gdb trace

```
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7805801 in __GI_abort () at abort.c:79
#2  0x00007fffb610bd4d in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#3  0x00007fffb610c9dd in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#4  0x00007fffb60d0637 in ?? () from /opt/rocm/hsa/lib/libhsa-runtime64.so.1
#5  0x00007ffff7bbd6db in start_thread (arg=0x7fffa1727700)
    at pthread_create.c:463
#6  0x00007ffff78e688f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by sunway513** [comment]
Hi @syoyo , Ubuntu18.04.2 is not supported by ROCm2.2, the related comment is here:
https://github.com/RadeonOpenCompute/ROCm/issues/731#issuecomment-472782999
Could you make sure your system can run HIP unit test correctly before trying tensorflow?
https://github.com/ROCm-Developer-Tools/HIP/tree/master/tests

**Comment by syoyo** [comment]
> Ubuntu18.04.2 is not supported by ROCm2.2, the related comment is here:
RadeonOpenCompute/ROCm#731 (comment)

I have confirmed same error happens on Ubuntu 16.04(2 Polaris'). FYI I'm using kernel 4.15 on Ubuntu 18.04.2

> Could you make sure your system can run HIP unit test correctly before trying tensorflow?

I've faced build failure of HIP tests(by following procedure of HIP tests readme)
Probably need to find a way to compile HIP tests without AMP support

```
/home/syoyo/work/HIP/tests/src/kernel/hipLanguageExtensions.cpp:34:10: fatal error: 'amp.h' file not found
#include <amp.h>
         ^~~~~~~
1 error generated.
/home/syoyo/work/HIP/tests/src/kernel/hipLanguageExtensions.cpp:34:10: fatal error: 'amp.h' file not found
#include <amp.h>
         ^~~~~~~
1 error generated.
CMake Error at /home/syoyo/work/HIP/build/install/cmake/FindHIP/run_make2cmake.cmake:18 (file):
  file failed to open for reading (No such file or directory):

    /home/syoyo/work/HIP/build/CMakeFiles/directed_tests.kernel.hipLanguageExtensions.dir/tests/src/kernel/directed_tests.kernel.hipLanguageExtensions_generated_hipLanguageExtensions.cpp.o.depend.pre


CMake Error at directed_tests.kernel.hipLanguageExtensions_generated_hipLanguageExtensions.cpp.o.cmake:134 (message):
  Error generating
  /home/syoyo/work/HIP/build/CMakeFiles/directed_tests.kernel.hipLanguageExtensions.dir/tests/src/kernel/./directed_tests.kernel.hipLanguageExtensions_generated_hipLanguageExtensions.cpp.o


CMakeFiles/directed_tests.kernel.hipLanguageExtensions.dir/build.make:63: recipe for target 'CMakeFiles/directed_tests.kernel.hipLanguageExtensions.dir/tests/src/kernel/directed_tests.kernel.hipLanguageExtensions_generated_hipLanguageExtensions.cpp.o' failed
make[3]: *** [CMakeFiles/directed_tests.kernel.hipLanguageExtensions.dir/tests/src/kernel/directed_tests.kernel.hipLanguageExtensions_generated_hipLanguageExtensions.cpp.o] Error 1
CMakeFiles/Makefile2:5675: recipe for target 'CMakeFiles/directed_tests.kernel.hipLanguageExtensions.dir/all' failed
make[2]: *** [CMakeFiles/directed_tests.kernel.hipLanguageExtensions.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[  2%] Built target directed_tests.kernel.inline_asm_vadd
[  3%] Built target directed_tests.kernel.hipTestConstant
[  3%] Built target directed_tests.kernel.hipGridLaunch
[  4%] Built target directed_tests.kernel.hipLaunchParmFunctor
[  5%] Built target directed_tests.kernel.hipPrintfKernel
[  5%] Built target directed_tests.kernel.hipTestMemKernel
[  6%] Built target directed_tests.kernel.hipLaunchParm
CMakeFiles/Makefile2:79: recipe for target 'CMakeFiles/build_tests.dir/rule' failed
make[1]: *** [CMakeFiles/build_tests.dir/rule] Error 2
Makefile:175: recipe for target 'build_tests' failed
```

I have also tried to compile RCCL sample program

https://github.com/ROCmSoftwarePlatform/rccl

and also got a memory access fault error.
So, it looks RCCL itself is not yet supported on ROCm 2.2?

**Comment by syoyo** [comment]
Filed an issue at RCCL repo: https://github.com/ROCmSoftwarePlatform/rccl/issues/59

**Comment by sunway513** [comment]
Hi @syoyo , thanks for the additional information.
Please aware RCCL support in TF1.13 and ROCm2.3 is experimental.
For multi-GPU training, we recommend using CPU as the parameter servers for better stability and performance.

**Comment by syoyo** [comment]
> Please aware RCCL support in TF1.13 and ROCm2.3 is experimental.

Oh, I see. I saw this comment from you and I thought RCCL is now available and working in ROCm: https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/155#issuecomment-461932571

I can use CPU node for corrective operation for a while, but official RCCL support in TensorFlow is highly expected.

**Comment by sunway513** [comment]
Thanks @syoyo , appreciate your comment. Will update when we have mature TF-RCCL solution available. 
Closing this ticket for now.

**Comment by ajitmaths** [comment]
We will have a mature RCCL support starting ROCm2.6... Stay tuned.

**Comment by syoyo** [comment]
@ajitmaths Awesome! Good to hear of it! > RCCL support starting ROCm2.6
