### ISSUE TITLE
`import os` is missing in `rccl_ops.py`

### ISSUE THREAD

**Issue by syoyo** [ROCmSoftwarePlatform/tensorflow-upstream#370]
**System information**

Same configuration with https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/369

**Code to reproduce the issue**

Please use test script described in:  https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/369

```
Traceback (most recent call last):
  File "./tesu2.py", line 16, in <module>
    y_pre = network(x)
  File "./tesu2.py", line 11, in network
    x0 = rccl.all_sum([x0,x1])
  File "/home/w/miniconda3/envs/py36_test/lib/python3.6/site-packages/tensorflow/contrib/rccl/python/ops/rccl_ops.py", line 49, in all_sum
    return _apply_all_reduce('sum', tensors)
  File "/home/w/miniconda3/envs/py36_test/lib/python3.6/site-packages/tensorflow/contrib/rccl/python/ops/rccl_ops.py", line 217, in _apply_all_reduce
    _validate_and_load_rccl_so()
  File "/home/w/miniconda3/envs/py36_test/lib/python3.6/site-packages/tensorflow/contrib/rccl/python/ops/rccl_ops.py", line 289, in _validate_and_load_rccl_so
    _maybe_load_rccl_ops_so()
  File "/home/w/miniconda3/envs/py36_test/lib/python3.6/site-packages/tensorflow/contrib/rccl/python/ops/rccl_ops.py", line 273, in _maybe_load_rccl_ops_so
    library_filename = os.path.join(resource_loader.get_data_files_path(),
NameError: name 'os' is not defined
```

We could simply add `import os` before line 273 to solve the issue.

**Comment by syoyo** [comment]
Thanks!
