### ISSUE TITLE
failed to memset memory: HIP_ERROR_InvalidValue (similar to #227)

### ISSUE THREAD

**Issue by jjkeijser** [ROCmSoftwarePlatform/tensorflow-upstream#522]
**System information**
- Linux CentOS 7.6 64bit
- TensorFlow-rocm installed from source
- TensorFlow 1.13.1
- Python 3.6 (rh-python-3.6)
- Installed using pip
- Bazel 0.21.0
- gcc 8.2.1
- ROCm/MIOpen 2.5.7 (latest from yum repo as of June 25th)
- Radeon VII 16 GB

First of all, a simple 'pip install tensorflow-rocm' installs a version of tensorflow that does not work in CentOS 7, due to a libm issue (2.23 needed, 2.17 present).
I then rebuilt tensorflow-rocm from source, select "rocm build" and installed the corresponding .whl file.
A very simple test of tf_cnn_benchmarks.py fails with the following log:

2019-06-26 14:40:39.693192: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2019-06-26 14:40:39.810050: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1531] Found device 0 with properties: 
name: Vega 20
AMDGPU ISA: gfx906
memoryClockRate (GHz) 1.802
pciBusID 0000:07:00.0
Total memory: 15.98GiB
Free memory: 15.73GiB
2019-06-26 14:40:39.810243: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1642] Adding visible gpu devices: 0
2019-06-26 14:40:39.810334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-26 14:40:39.810387: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1059]      0 
2019-06-26 14:40:39.810437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1072] 0:   N 
2019-06-26 14:40:39.810628: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1189] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15306 MB memory) -> physical GPU (device: 0, name: Vega 20, pci bus id: 0000:07:00.0)
2019-06-26 14:40:43.521556: E tensorflow/stream_executor/rocm/rocm_driver.cc:461] failed to memset memory: HIP_ERROR_InvalidValue
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to memcopy into scratch buffer for device 0
	 [[{{node _SOURCE}}]]

the rocm stack itself is working, tools like rocminfo, rocm_bandwidth_test  and mixbench all report meaningful results.  What can I do to debug this?

**Comment by sunway513** [comment]
Hi @jjkeijser , for CentOS distro, we recommend using our docker images, you can find more instructions here:
https://hub.docker.com/r/rocm/tensorflow

ROCm requires devtoolset7 to be configured before the HIP/HCC toolset can function correctly on CentOS user bits, mainly to fulfill the GCC version dependency.

**Comment by jjkeijser** [comment]
I've tested the docker image and that does work (with good performance, actually!)
However, I'd like to run it without docker; the code builds using either devtoolset-7 or devtoolset-8, it's just that I cannot get beyond the error mentioned above. Also, I noticed that the error code that is returned for the HipMemset function *always* seems to be InvalidValue - so I have no idea where it is failing.
How can I debug this further?  (if need be, remote access to the system can be arranged).

**Comment by sunway513** [comment]
Thanks @jjkeijser , glad to know the docker image approach can work on your side. 
Please note, due to the limited bandwidth, we won't be able to support TF-ROCm project on CentOS user bit configurations for community users; thank you for the understanding. 
However, we do have an experimental Dockerfile that can build Tensorflow-rocm 1.13 release branch correctly for CentOS distro. You can find it [here](https://www.dropbox.com/s/30f3b143hbomlps/tensorflow-centos-dockerfile.tar), and hopefully that can be helpful for your explorations.

**Comment by jjkeijser** [comment]
For the record: with the aid of the Dockerfile above I was able to build tensorflow-rocm (natively, not using docker) and it runs even faster than inside the docker container. The only minor issue remaining is the slow startup time, caused by these messages:
```
2019-07-04 09:54:57.089425: I tensorflow/core/kernels/conv_grad_filter_ops.cc:979] running auto-tune for Backward-Filter
2019-07-04 09:54:59.756359: I tensorflow/core/kernels/conv_grad_input_ops.cc:1027] running auto-tune for Backward-Data
```

**Comment by sunway513** [comment]
@jjkeijser , thanks for the update.
FYI, MIOpen compiles the kernels on the fly when you see those auto-tune message from TF. This is a one-time effort (for the particular release), the second time you run the TF benchmark MIOpen runtime can fetch the compiled kernels from the `~/.cache/miopen`, therefore you won't see the warmup slowness.

**Comment by zbwu** [comment]
@jjkeijser Hi, I had the same issue, I have cherry-pick #194 to fixed it. But I don't know why.
