### ISSUE TITLE
Tensorflow ROCm libmcwamp.so import error

### ISSUE THREAD

**Issue by Krish12003** [ROCmSoftwarePlatform/tensorflow-upstream#539]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary):  PyPi
- TensorFlow version: Name: tensorflow-rocm
                                    Version: 1.13.3

- Python version: 3.7.3
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- ROCm/MIOpen version: Package: rocm-libs
                                          Version: 2.5.27

- GPU model and memory: RX 580 8 GB

**Describe the problem**

Everything was working fine before. I wanted to switch from anaconda to just cpython, therefore I uninstalled anaconda and then uninstalled rocm. I reinstalled rocm and python 3.7.3 and then also tensorflow-rocm. Then this issue arose, where I am unable to use tensorflow. Full Traceback below.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

import tensorflow
print(tensorflow.__version__)

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Traceback (most recent call last):
  File "/home/krish/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/krish/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/krish/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libmcwamp.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "classify_image.py", line 46, in <module>
    import tensorflow as tf
  File "/home/krish/.local/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/krish/.local/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/krish/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/krish/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/krish/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/krish/.local/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libmcwamp.so: cannot open shared object file: No such file or directory

**Comment by sunway513** [comment]
@Krish12003 , do you have the following file?
_$:/opt/rocm/lib# ll libmcwamp.so 
lrwxrwxrwx 1 root root 30 Jul  4 20:01 libmcwamp.so -> /opt/rocm/hcc/lib/libmcwamp.so_
If not, please use the following command to uninstall your rocm user bits, and then follow the tensorflow-rocm[ installation instruction](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-install-basic.md) to try again:
`sudo apt autoremove -y rocm_bandwidth_test rocminfo hsakmt-roct hsa-rocr-dev rocm-cmake hsa-ext-rocr-dev rocm-device-libs hip_base hip_samples`

**Comment by Krish12003** [comment]
I did the reinstall, now missing

libhc_am.so

according to the error

**Comment by sunway513** [comment]
@Krish12003 , did you run the following commands after cleaning up your rocm environment?
`sudo apt-get update && \
    sudo apt-get install -y --allow-unauthenticated \
    rocm-dkms rocm-dev rocm-libs rccl \
    rocm-device-libs \
    hsa-ext-rocr-dev hsakmt-roct-dev hsa-rocr-dev \
    rocm-opencl rocm-opencl-dev \
    rocm-utils \
    rocm-profiler cxlactivitylogger \
    miopen-hip miopengemm`

**Comment by sunway513** [comment]
@Krish12003  please provide the logs from the following command if you still see issues:
`apt --installed list | grep -E 'hip|hcc|roc|miopen|amdgpu|hsa'`

**Comment by Bengt** [comment]
I ran into the same problem after upgrading to rocm 3.0. The full stacktrace for improved visibility in search engines:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libmcwamp.so.2: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/pfasdr/neural/ze_discriminate_pd_np_linear.py", line 9, in <module>
    from pfasdr.neural.ze_discriminate_pd_np.learn_grid_constraints_module import \
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/pfasdr/neural/ze_discriminate_pd_np/learn_grid_constraints_module.py", line 5, in <module>
    from keras import Model
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/tensorflow_core/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/bengt/Projekte/gitlab.com/PFASDR/PFASDR.Code.Main/.tox/py36-neural-rocm/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libmcwamp.so.2: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Process finished with exit code 1
```

Seems like the library name has changed from `.2` to `.3`, but the symbols stayed largely the same. So I fixed this issue by linking the old name to the new binary:

    cd /opt/rocm/lib
    sudo ln -s libmcwamp.so.3.0 libmcwamp.so.2

... or as a oneliner:

    sudo ln -s /opt/rocm/lib/libmcwamp.so.3.0 /opt/rocm/lib/libmcwamp.so.2

**Comment by sunway513** [comment]
@Bengt Thanks for reporting the issue. Just FYI, we didn't see such issue using rocm/tensorflow docker containers built with ROCM3.0, hence this issue is likely caused by some obsoleted packages on your system during upgrade.
Please let me know if you can reproduce the issue in docker containers, thanks.

**Comment by Bengt** [comment]
I see the issue with `rocm/tensorflow:rocm3.0-tf2.0-python3`:

https://gitlab.com/pfasdr/code/main/-/jobs/400589470#L249
https://gitlab.com/pfasdr/code/main/-/jobs/400589469#L237

**Comment by fakhrirobi** [comment]
Can anybody help me, im a new learner at ubuntu, i installed rocm for tensorflow , then i imported tensorflow as usual and this happened :
Traceback (most recent call last):
  File "/home/fakhri/env/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: librccl.so.1: cannot open shared object file: No such file or directory

**Comment by xuhuisheng** [comment]
@fakhrirobi 
please install rccl first. For example, on Ubuntu `sudo apt install rccl`

**Comment by Bengt** [comment]
@fakhrirobi you are commenting on a closed issue about something else. Please try to find an issue relevant to your problem. The error message you are seeing has already been discussed: https://github.com/RadeonOpenCompute/ROCm/issues/1161
