### ISSUE TITLE
ROCm 2.4 cannot import tensorflow

### ISSUE THREAD

**Issue by zjunweihit** [ROCmSoftwarePlatform/tensorflow-upstream#543]
**System information**
- Ubuntu 18.04.1
- kernel: 4.15.0-54-generic
- ROCm 2.4-25
- Python 3.6.8
- tensorflow-rocm 1.13.3
- miopen 1.8.1

**Device**
- Radeon VII(vega20, 16G): VEGA20 0x1002:0x66AF 0x1002:0x081E 0xC1

**Install**
- installed by pip3, not in virtualenv
```
pip3 install tensorflow-rocm
```
**Describe the problem**
Cannot import tensorflow,  **which works when I played with ROCm 2.0, tensorlfow 1.12.0**
```
import tensorflow as tf
```

**Any other info / logs**

```
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/home/zjunwei/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/zjunwei/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/zjunwei/.local/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /opt/rocm/bin/../lib/librocfft-device.so.0: undefined symbol: _ZN8hip_impl13program_stateD1Ev

```

**Comment by sunway513** [comment]
Hi @zjunweihit , can you provide the logs of the following command?
`apt --installed list | grep rocfft`

**Comment by zjunweihit** [comment]
Hi @sunway513 
```#bash
apt --installed list | grep rocfft

rocfft/now 0.9.3.0 amd64 [installed,upgradable to: 0.9.4.0]
```

**Comment by zjunweihit** [comment]
upgrade ROCm to 2.6, since I get the notice today.
everything works well now :)

**Comment by sunway513** [comment]
Thanks for the update :-)
