### ISSUE TITLE
Crash when performing inference

### ISSUE THREAD

**Issue by thejinx0r** [ROCmSoftwarePlatform/tensorflow-upstream#604]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): I suppose. I'm using a software package that uses tensorflow-gpu under the hood, but I manually installed tensorflow-rocm in to their environment.

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
Ubuntu 18.04

- TensorFlow installed from (source or binary): from pypi binary
- TensorFlow version (use command below): 1.14.1 (Problem also occurs on 1.14.0, I can't test it on 1.13.x)
- Python version: 3.6.2
- ROCm/MIOpen version:
```
miopen-hip/Ubuntu 16.04,now 2.0.1.7405-rocm-rel-2.7-22-4e39a83 amd64 [installed]
  AMD's DNN Library

miopen-opencl/Ubuntu 16.04 2.0.1.7405-rocm-rel-2.7-22-4e39a83 amd64
  AMD's DNN Library

miopengemm/Ubuntu 16.04,now 1.1.6.645-rocm-rel-2.7-22-6275a87 amd64 [installed]
  A tool for generating OpenCL matrix multiplication (GEMM) kernels
```
- GPU model and memory:
Vega 7 16GB

**Describe the current behavior**

I don't know the entire lingo, as I'm new to all of this and I didn't implement any of the tensorflow stuff. 

So I used a software package that uses tensorflow-gpu to perform Deep Learning. My colleages have generated a few networks and it works on their machines and others that have a nvidia card.

When I try using those networks on my computer, with tensorflow-rocm, and I try to use those trained networks for inference, it crashes my computer. Like it reboots itself. 

The networks are saved in h5 format. I haven't tried just generating a new network and training a new network. 

**Describe the expected behavior**
For it to not crash my whole computer. At least only crash python.

**Other info / logs**

It's been a while that I have installed rocm, so I don't remember how I did it, but is it normal that my miopen packages are called ubuntu 16.04 but I'm on ubuntu 18.04?

The Vega is also driving my desktop environment.

**Comment by sunway513** [comment]
Hi @thejinx0r , the ROCm packages were generated from UB16.04 host, to your last question - yes, that's okay. 
We need exact steps to reproduce your issue locally before we can provide any meaningful suggestions.

**Comment by thejinx0r** [comment]
I have been using a proprietary software package called Dragonfly by Object Research Systems.
I will try to extract a minimal working example that is independent of their proprietary binaries.

While replying, I thought maybe I should update my gpu drivers, as I'm using the amdgpu-pro drivers (19.30 installed now, I was on 19.10 before). I know it shouldn't make a difference, but just in case.

I now get an actual error as opposed to crashing:
```
2019-08-19 10:24:46.871728: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libMIOpen.so
MIOpen(HIP): Error [FindRecordUnsafe] Ill-formed record: key not found: /home/eric/.config/miopen//gfx906_60.HIP.2_0_1.ufdb.txt#459
MIOpen(HIP): Error [FindRecordUnsafe] Ill-formed record: key not found: /home/eric/.config/miopen//gfx906_60.HIP.2_0_1.ufdb.txt#459
MIOpen Error: basic_string::_M_construct null not valid
2019-08-19 10:24:47.025310: F tensorflow/stream_executor/rocm/rocm_dnn.cc:2707] Check failed: status == miopenStatusSuccess (7 vs. 0)Unable to find a suitable algorithm for doing forward convolution
```

**Comment by sunway513** [comment]
Hi @thejinx0r , thanks, a reduced case would be very helpful.
In the meanwhile, we might be able to reduce the failure on MIOpen level. Can you provide the logs with after setting the following environment variable?
```
export HCC_SERIALIZE_KERNEL=3 
export HCC_SERIALIZE_COPY=3 
export MIOPEN_LOG_LEVEL=6
export MIOPEN_ENABLE_LOGGING=1
```
Please note the log would be pretty large, you might want to attach the file instead of just pasting.

**Comment by thejinx0r** [comment]
Ok, so as I was trying it, I came across a few different things.

My computer is still crashing. This only happens either during training or inference. Meaning it was able to load MIOpen. I thought it might have been due to lack of power (I have Radeon VII and a GTX 2060 for use in a VM), but after unplugging the GTX, it still crashes. 

I copy pasted the output to paste bin:
https://pastebin.com/N0wySYWY

As I mentioned before, I'm using it in a closed source binary that calls tensorflow, so I only included the portion of the output when I started training.

In the logs, there's little snippet:
```
MIOpen(HIP): Info2 [StoreRecordUnsafe] Storing record: 1-512-512-3x3-64-512-512-1-1x1-1x1-1x1-0-NCHW-FP32-F
MIOpen(HIP): Info2 [FindRecordUnsafe] Looking for key 1-512-512-3x3-64-512-512-1-1x1-1x1-1x1-0-NCHW-FP32-F in file /home/eric/.config/miopen//gfx906_60.HIP.2_0_1.ufdb.txt
MIOpen(HIP): Info2 [Measure] Db::StoreRecord time: 0.401661 ms
MIOpen Error: basic_string::_M_construct null not valid
```
I looked in the ufdb.txt file, and surprisingly, that key is not there. So the error `MIOpen Error: basic_string::_M_construct null not valid` makes sense if you never validate that the string is stored correctly.

For the actual crash, it seems to occur predominantly on larger patch sizes. For this particular dataset, I wanted to use large patches (>128), but that's when it seems to crash. I tried patch sizes of 32 and it works.

**Comment by sunway513** [comment]
@JehandadKhan @daniellowell , can you help review the logs? 
It seems like a failure inside MIOpen findalgo.

**Comment by daniellowell** [comment]
@thejinx0r You can work around this by setting the environment variable:
`MIOPEN_DEBUG_DISABLE_FIND_DB=1`
Meanwhile we will investigate.

**Comment by atamazov** [comment]
@thejinx0r please attach your `/home/eric/.config/miopen//gfx906_60.HIP.2_0_1.ufdb.txt`, thanks.

**Comment by thejinx0r** [comment]
@atamazov 
I put my db file on pastebin
https://pastebin.com/zsw1inJX

**Comment by atamazov** [comment]
Great, thanks! Could you please also attach the _file_ here? It should be easy to do. Drag'n'drop works for me, for example.

**Comment by thejinx0r** [comment]
[gfx906_60.HIP.2_0_1.ufdb.txt](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/files/3517856/gfx906_60.HIP.2_0_1.ufdb.txt)

@atamazov  Great! I was looking for an icon to drop files!

**Comment by thejinx0r** [comment]
@daniellowell 
I still have the same issue after setting
`MIOPEN_DEBUG_DISABLE_FIND_DB=1`

**Comment by atamazov** [comment]
> While replying, I thought maybe I should update my gpu drivers, as I'm using the amdgpu-pro drivers (19.30 installed now, I was on 19.10 before). I know it shouldn't make a difference, but just in case.

IIRC MIOpen cannot work on top of AMDGPU-Pro drivers. You need ROCm to use it.

How to quickly check your MIOpen installation:
- Build MIOpenDriver
- Run `.../MIOpenDriver conv -c 1 -H 512 -W 512 -y 3 -x 3 -k 64 -n 1 -p 1 -q 1 -w 1 -t 1 -V 0 -F 1`. This command runs exactly the convolution which fails on your machine (according to the logs you've provided). Output from my machine:
```
atamazov@panzerfaust:~/github/MLOpen2/build/Release.HIP$ ./bin/MIOpenDriver conv -c 1 -H 512 -W 512 -y 3 -x 3 -k 64 -n 1 -p 1 -q 1 -w 1 -t 1 -V 1 -F 1
MIOpenDriver: conv -c 1 -H 512 -W 512 -y 3 -x 3 -k 64 -n 1 -p 1 -q 1 -w 1 -t 1 -V 1 -F 1
Wall-clock Time Forward Conv. Elapsed: 0.180096 ms, Auxiliary API calls: 1634.79 ms
MIOpen Forward Conv. Algorithm: 1
GPU Kernel Time Forward Conv. Elapsed: 0.124231 ms (average)
stats: name, n, c, ho, wo, x, y, k, flopCnt, bytesRead, bytesWritten, GFLOPs, GB/s, timeMs
stats: fwd-conv3x3u1, 1, 1, 512, 512, 3, 3, 64,  301989888, 1050880, 67108864, 2431, 549, 0.124231
Forward Convolution Verifies on CPU and GPU (1.46496e-08)
```

- MIOpen installation instructions: https://github.com/ROCmSoftwarePlatform/MIOpen
- ROCm installation: https://github.com/RadeonOpenCompute/ROCm.

**Comment by sunway513** [comment]
@thejinx0r , it's not recommended to mix the usage of amdgpu-pro drivers and rock-dkms driver - that can be the root cause of the failure you've observed.  
Can you purge the amdgpu-pro driver and reinstall rock-dkms driver on your system?

**Comment by thejinx0r** [comment]
@atamazov 
It was working with patch size 32. Does that mean that it was falling back on the cpu?
It did seem a little slow, but I wasn't sure. 

@atamazov @sunway513 
For uninstalling amdgpu-pro, it's not possible in my case.
I need 3D rendering with an OpenGL version that mesa doesn't support yet.
Does that mean it will never work on my computer? Or does it mean that it could work, but no one is actively making it work?

**Comment by atamazov** [comment]
@thejinx0r 
> It was working with patch size 32. 

Batch size? From the log I see batch size = 1.

> Does that mean that _it_ was falling back on the cpu?

I do not fully understand _what_ was falling back. MIOpen wouldn't.

**Comment by thejinx0r** [comment]
@atamazov 
When I get a chance, I will post a log. But it was patch size 32, batch size 512.

**Comment by sunway513** [comment]
CC @kentrussell to comment.
My understanding is that QA team doesn't test against such kernel driver combination (amdgpu-pro + rock-dkms) for Linux distros, nor it's recommended. 
However, since amdgpu-pro consists of the essential kernel module (amdgpu) that is required to support ROCm user bits, your setup might work, however, YMMV.

**Comment by atamazov** [comment]
@thejinx0r The log previously published by you [here](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/604#issuecomment-522667459) is saying that failing convolution uses batch size = 1.

**Comment by thejinx0r** [comment]
@atamazov 
Yes, the patch size 512 and any batch size does not work (log shown with batch size 1), but a patch size of 32 batch size 512 ( log not shown yet) worked.

@sunway513 
Oh ok. I misunderstood. I will give it a try.
I thought uninstalling amdgpu-pro implied using the mesa drivers.

**Comment by kentrussell** [comment]
@sunway513 Agreed. We only do real testing of ROCk+ROCm for releases. While there is some theoretical support for amdgpu-pro+ROCm (since the codebase is similar), there are some memory pool changes that are incorporated into ROCk that are absent from amdgpu-pro and other issues that may arise. Thus we can't guarantee anything outside of the officially supported ROCk+ROCm configuration.

**Comment by sunway513** [comment]
@thejinx0r , can you try to run the HIP unit tests before moving to TF benchmarks?
Here's the instructions:
https://github.com/ROCm-Developer-Tools/HIP/tree/master/tests

**Comment by thejinx0r** [comment]
@sunway513 
Finally got around to testing it:
```
100% tests passed, 0 tests failed out of 132
Total Test time (real) = 135.62 sec
```

**Comment by sunway513** [comment]
@thejinx0r , great to know all HIP tests now pass.
Can you follow the doc and run a set of TF samples:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-quickstart.md

**Comment by thejinx0r** [comment]
@sunway513 
That fails:

```
models/tutorials/image/mnist
W0913 14:10:52.832289 140425595361088 deprecation_wrapper.py:119] From convolutional.py:340: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0913 14:10:52.832847 140425595361088 deprecation_wrapper.py:119] From convolutional.py:65: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.

W0913 14:10:52.832995 140425595361088 deprecation_wrapper.py:119] From convolutional.py:66: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0913 14:10:53.453325 140425595361088 deprecation_wrapper.py:119] From convolutional.py:70: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
W0913 14:10:54.334942 140425595361088 deprecation_wrapper.py:119] From convolutional.py:153: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0913 14:10:54.347975 140425595361088 deprecation_wrapper.py:119] From convolutional.py:165: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.

W0913 14:10:54.382505 140425595361088 deprecation_wrapper.py:119] From convolutional.py:201: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W0913 14:10:54.389010 140425595361088 deprecation.py:506] From convolutional.py:226: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
W0913 14:10:54.410363 140425595361088 deprecation_wrapper.py:119] From convolutional.py:244: The name tf.train.exponential_decay is deprecated. Please use tf.compat.v1.train.exponential_decay instead.

W0913 14:10:54.416074 140425595361088 deprecation_wrapper.py:119] From convolutional.py:251: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

W0913 14:10:54.549195 140425595361088 deprecation_wrapper.py:119] From convolutional.py:285: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-09-13 14:10:54.549482: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libhip_hcc.so
2019-09-13 14:10:54.626384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1651] Found device 0 with properties:
name: Vega 20
AMDGPU ISA: gfx906
memoryClockRate (GHz) 1.801
pciBusID 0000:04:00.0
2019-09-13 14:10:54.652504: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library librocblas.so
2019-09-13 14:10:54.662587: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libMIOpen.so
2019-09-13 14:10:54.664252: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library librocfft.so
2019-09-13 14:10:54.664712: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library librocrand.so
2019-09-13 14:10:54.664856: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-09-13 14:10:54.665308: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2019-09-13 14:10:54.676571: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3700085000 Hz
2019-09-13 14:10:54.677081: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d6ccc94630 executing computations on platform Host. Devices:
2019-09-13 14:10:54.677109: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-09-13 14:10:54.677308: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1651] Found device 0 with properties:
name: Vega 20
AMDGPU ISA: gfx906
memoryClockRate (GHz) 1.801
pciBusID 0000:04:00.0
2019-09-13 14:10:54.677376: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library librocblas.so
2019-09-13 14:10:54.677412: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libMIOpen.so
2019-09-13 14:10:54.677448: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library librocfft.so
2019-09-13 14:10:54.677484: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library librocrand.so
2019-09-13 14:10:54.677572: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-09-13 14:10:54.677661: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-09-13 14:10:54.677682: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0
2019-09-13 14:10:54.677703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N
2019-09-13 14:10:54.677880: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15306 MB memory) -> physical GPU (device: 0, name: Vega 20, pci bus id: 0000:04:00.0)
2019-09-13 14:10:54.680278: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d6d0201c30 executing computations on platform ROCM. Devices:
2019-09-13 14:10:54.680303: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Vega 20, AMDGPU ISA version: gfx906
W0913 14:10:54.681385 140425595361088 deprecation_wrapper.py:119] From convolutional.py:287: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

Initialized!
2019-09-13 14:11:30.403411: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library librocblas.so
2019-09-13 14:11:30.405697: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libMIOpen.so
MIOpen Error: /root/driver/MLOpen/src/ocl/handleocl.cpp:332: Error: Creating Handle. Cannot Initialize Handle from Queue Invalid Command Queue
2019-09-13 14:11:30.405929: E tensorflow/stream_executor/rocm/rocm_dnn.cc:532] could not create miopen handle: miopenStatusUnknownError
2019-09-13 14:11:30.405950: W ./tensorflow/stream_executor/stream.h:2086] attempting to perform DNN operation using StreamExecutor without DNN support
Traceback (most recent call last):
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Failed to find conv algorithm!
         [[{{node Conv2D}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "convolutional.py", line 340, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "convolutional.py", line 301, in main
    sess.run(optimizer, feed_dict=feed_dict)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Failed to find conv algorithm!
         [[node Conv2D (defined at convolutional.py:196) ]]

Errors may have originated from an input operation.
Input Source operations connected to node Conv2D:
 Variable/read (defined at convolutional.py:167)
 Placeholder (defined at convolutional.py:155)

Original stack trace for 'Conv2D':
  File "convolutional.py", line 340, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "convolutional.py", line 230, in main
    logits = model(train_data_node, True)
  File "convolutional.py", line 196, in model
    padding='SAME')
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1953, in conv2d
    name=name)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/eric/ors_dragonfly_python/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


```

**Comment by sunway513** [comment]
@thejinx0r , it's strange - can you confirm if you are using docker container or bare metal setup?
It does look like configuration issue if the setup can not pass basic TF samples.

**Comment by thejinx0r** [comment]
@sunway513 
I am on bare metal.

**Comment by sunway513** [comment]
To rule out the potential configuration issues, can you try our docker containers?
https://hub.docker.com/r/rocm/tensorflow

**Comment by thejinx0r** [comment]
@sunway513 
So it does seem like a configuration issue as you suspect.
I followed the instructions for running tensorflow inside of docker, the LeNet MNIST ran properly and it was running the `ResNet training on CIFAR-10 data` but I cancelled it because it was going to take a while to run.

**Comment by thejinx0r** [comment]
I'm closing the issue for now as I need to switch back to the amd-pro drivers for the moment. I'm not sure when I will be able to get back to it.
