### ISSUE TITLE
Not able to install Tensorflow 

### ISSUE THREAD

**Issue by computingdolas** [ROCmSoftwarePlatform/tensorflow-upstream#86]
You are using pip version 6.1.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Cannot uninstall requirement tensorflow, not installed
........
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'rocm/build_defs.bzl': no such package '@local_config_rocm//rocm': Traceback (most recent call last):
	File "/data/home/sagard/tensorflow-1.8/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 624
		_create_local_rocm_repository(repository_ctx)
	File "/data/home/sagard/tensorflow-1.8/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 529, in _create_local_rocm_repository
		_find_libs(repository_ctx, rocm_config)
	File "/data/home/sagard/tensorflow-1.8/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 304, in _find_libs
		_find_rocm_lib("hip_hcc", repository_ctx, cpu_value, ...)
	File "/data/home/sagard/tensorflow-1.8/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 289, in _find_rocm_lib
		auto_configure_fail(("Cannot find rocm library %s" %...))
	File "/data/home/sagard/tensorflow-1.8/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 101, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find rocm library libhip_hcc.so
WARNING: Target pattern parsing failed.
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'rocm/build_defs.bzl': no such package '@local_config_rocm//rocm': Traceback (most recent call last):
	File "/data/home/sagard/tensorflow-1.8/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 624
		_create_local_rocm_repository(repository_ctx)
	File "/data/home/sagard/tensorflow-1.8/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 529, in _create_local_rocm_repository
		_find_libs(repository_ctx, rocm_config)
	File "/data/home/sagard/tensorflow-1.8/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 304, in _find_libs
		_find_rocm_lib("hip_hcc", repository_ctx, cpu_value, ...)
	File "/data/home/sagard/tensorflow-1.8/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 289, in _find_rocm_lib
		auto_configure_fail(("Cannot find rocm library %s" %...))
	File "/data/home/sagard/tensorflow-1.8/tensorflow-upstream/third_party/gpus/rocm_configure.bzl", line 101, in auto_configure_fail
		fail(("\n%sCuda Configuration Error:%...)))

Cuda Configuration Error: Cannot find rocm library libhip_hcc.so
INFO: Elapsed time: 0.486s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package

------------------------

### System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
OS Platform and Distribution (Centos 7)**:
TensorFlow version (1.8)**:
Python version - 2,7.10
Bazel version (0.10.0)**:
GCC/Compiler version (gcc 7.3)**:
GPU model and memory - gfx900

**Comment by sunway513** [comment]
Hi @computingdolas , the published TF whl file won't install on centos7.
Instead, we provide docker solutions, please follow the instructions [here](https://github.com/RadeonOpenCompute/ROCm-docker/blob/master/quick-start.md) and use the following docker image:
rocm/tensorflow:rocm1.8.2-tf1.8-centos-python3

**Comment by computingdolas** [comment]
Thank you @sunway513  . I had actually installed tensorflow-1.3 room port on centos 7 just 2 weeks ago. I will the docker solution and meanwhile am looking forward to see working solution for centos 7.

**Comment by sunway513** [comment]
Hi @computingdolas , yes, it's definitely possible to install TF1.8 on centos, you can actually get the whl file from the docker image I've cited, supposing you have correctly configured the ROCm environment on your local node.

**Comment by sunway513** [comment]
Close this ticket, please feel free to open it with further questions/updates.
