### ISSUE TITLE
An error occurred during the fetch of repository 'io_bazel_rules_docker'

### ISSUE THREAD

**Issue by Una-Tian** [ROCmSoftwarePlatform/tensorflow-upstream#940]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.2
- Python version: 3.6.8
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 2.0.0
- GCC/Compiler version (if compiling from source): 7.5.0
- ROCm/MIOpen version: 3.3
- GPU model and memory: 16G

**Describe the problem**
Bazel build in docker images rocm/dev-ubuntu-18.04:3.3 from source. I got error in 2.8s after run build_rocm_xla_python3.
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_docker':
   Traceback (most recent call last):
error running 'git init /root/Tensorflow/bazel_out/external/io_bazel_rules_docker' while working with @io_bazel_rules_docker:
src/main/tools/process-wrapper-legacy.cc:58: "execvp(git, ...)": No such file or directory

2.8s is short. It may be not the reason of network rate. Thx. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**
TF_PKG_LOC=/root/Tensorflow/tensorflow_pkg
rm -f $TF_PKG_LOC/tensorflow*.whl
yes "" | ROCM_PATH=/opt/rocm-3.3.0 TF_NEED_ROCM=1 TF_ENABLE_XLA=1 PYTHON_BIN_PATH=/root/Python/install/bin/python3 ./configure
bazel --output_base=/root/Tensorflow/bazel_out  build \
        --config=opt --config=rocm //tensorflow/tools/pip_package:build_pip_package --verbose_failures --local_ram_resources=4096 &&
bazel-bin/tensorflow/tools/pip_package/build_pip_package $TF_PKG_LOC &&
pip3 install --upgrade $TF_PKG_LOC/tensorflow*.whl

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
INFO: Found applicable config definition build:dynamic_kernels in file /root/Tensorflow/tensorflow-upstream/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Call stack for the definition of repository 'io_bazel_rules_docker' which is a git_repository (rule definition at /root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
 - /root/Tensorflow/bazel_out/external/bazel_toolchains/repositories/repositories.bzl:37:9
 - /root/Tensorflow/tensorflow-upstream/WORKSPACE:37:1
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_docker':
   Traceback (most recent call last):
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
		_clone_or_update(ctx)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(<1 more arguments>)
error running 'git init /root/Tensorflow/bazel_out/external/io_bazel_rules_docker' while working with @io_bazel_rules_docker:
src/main/tools/process-wrapper-legacy.cc:58: "execvp(git, ...)": No such file or directory
ERROR: no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
		_clone_or_update(ctx)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(<1 more arguments>)
error running 'git init /root/Tensorflow/bazel_out/external/io_bazel_rules_docker' while working with @io_bazel_rules_docker:
src/main/tools/process-wrapper-legacy.cc:58: "execvp(git, ...)": No such file or directory
ERROR: no such package '@io_bazel_rules_docker//repositories': Traceback (most recent call last):
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git.bzl", line 177
		_clone_or_update(ctx)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, in _clone_or_update
		git_repo(ctx, directory)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, in git_repo
		_update(ctx, git_repo)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, in _update
		init(ctx, git_repo)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 115, in init
		_error(ctx.name, cl, st.stderr)
	File "/root/Tensorflow/bazel_out/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 181, in _error
		fail(<1 more arguments>)
error running 'git init /root/Tensorflow/bazel_out/external/io_bazel_rules_docker' while working with @io_bazel_rules_docker:
src/main/tools/process-wrapper-legacy.cc:58: "execvp(git, ...)": No such file or directory
INFO: Elapsed time: 2.807s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
(END)

**Comment by sunway513** [comment]
Hi @Una-Tian , it seems you are missing some dependencies. 
Can you try with our pre-configured dev docker container below, instead of the ROCm 18.04 base docker?
`rocm/tensorflow:rocm3.3-tf2.2-rc2-dev`

**Comment by ekuznetsov139** [comment]
It sounds like the docker image does not have git installed. Try to run
```apt-get update```
```apt-get install git```

**Comment by gmt710** [comment]
@ekuznetsov139 It works for me.Thanks for your sharing.

**Comment by YenTran32** [comment]
@ekuznetsov139 Many thanks.

**Comment by cuisonghui** [comment]
@ekuznetsov139  thanks a lot，solved my problem
