### ISSUE TITLE
Tensorflow ROCM supporting new ROCM 3.5 version?

### ISSUE THREAD

**Issue by oscarbg** [ROCmSoftwarePlatform/tensorflow-upstream#998]
Hi,
are ROCM 3.5 enabled builds of tensorflow-rocm package coming soon..
as I updated to ROCM 3.5 (which seems to remove HCC) and existing tensorflow-rocm installation has error finding libmcwamp.so or something similar.. seems missing from ROCM 3.5 repo and related to removal of HCC..
searching https://pypi.org/project/tensorflow-rocm/#history
seems there are recent ones 2.2rc builds so I installed with command similar to:
pip install tensorflow-rocm==2.2.0rc5
but still seems these builds require ROCM 3.3 or lower..
can we expect final TF2.2 ROCM build support 3.5? if not any other way of obtaining any TF ROCM supporting new ROCM 3.5? or any ETA?
 thanks..

**Comment by sunway513** [comment]
Hi @oscarbg , yes, we are working on the wheel packages and will update soon.

**Comment by sunway513** [comment]
Hi @oscarbg , we've released the tensorflow-rocm packages built with ROCm3.5 environment.
For details please refer to the following document:
https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/blob/develop-upstream/rocm_docs/tensorflow-rocm-release.md

**Comment by oscarbg** [comment]
Hi @sunway513 ,
thanks.. that was quick..
upon quick testing seems there is a bug in rocblas running aibench (are you aware?)
just after aibench 8.1 test I get:
```
8.1 - inference | batch=10, size=512x512: 320 ± 3 ms
MIOpen Error: /root/driver/MLOpen/src/gemm_v2.cpp:523: rocBlas error encountered
Memory access fault by GPU node-1 (Agent handle: 0x45757c0) on address 0x1c000. Reason: Page not present or supervisor privilege.
```

full log with dmesg with sensible info:

```
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ai_benchmark import AIBenchmark
>>> results = AIBenchmark().run()

>>   AI-Benchmark-v.0.1.2   
>>   Let the AI Games begin..

*  TF Version: 2.2.0
*  Platform: Linux-5.7.0-050700-generic-x86_64-with-glibc2.29
*  CPU: Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
*  CPU RAM: 31 GB
*  GPU/0: Vega 10 XL/XT [Radeon RX Vega 56/64]
*  GPU RAM: 7.2 GB
*  CUDA Version: N/A
*  CUDA Build: N/A

The benchmark is running...
The tests might take up to 20 minutes
Please don't interrupt the script

1/19. MobileNet-V2

1.1 - inference | batch=50, size=224x224: 2078 ± 5 ms
1.2 - training  | batch=50, size=224x224: 9222 ± 41 ms

2/19. Inception-V3

2.1 - inference | batch=20, size=346x346: 467 ± 2 ms
2.2 - training  | batch=20, size=346x346: 2749 ± 12 ms

3/19. Inception-V4

3.1 - inference | batch=10, size=346x346: 424 ± 1 ms
3.2 - training  | batch=10, size=346x346: 2024 ± 8 ms

4/19. Inception-ResNet-V2

4.1 - inference | batch=10, size=346x346: 384.8 ± 0.5 ms
4.2 - training  | batch=8, size=346x346: 1640 ± 8 ms

5/19. ResNet-V2-50

5.1 - inference | batch=10, size=346x346: 194 ± 2 ms
5.2 - training  | batch=10, size=346x346: 652.9 ± 0.5 ms

6/19. ResNet-V2-152

6.1 - inference | batch=10, size=256x256: 432 ± 2 ms
6.2 - training  | batch=10, size=256x256: 1027 ± 5 ms

7/19. VGG-16

7.1 - inference | batch=20, size=224x224: 731 ± 10 ms
7.2 - training  | batch=2, size=224x224: 679 ± 10 ms

8/19. SRCNN 9-5-5

8.1 - inference | batch=10, size=512x512: 318.5 ± 0.5 ms
MIOpen Error: /root/driver/MLOpen/src/gemm_v2.cpp:523: rocBlas error encountered
Traceback (most recent call last):
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1349, in _run_fn
    return self._call_tf_sessionrun(options, feed_dict, fetch_list,
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1441, in _call_tf_sessionrun
    return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: cuDNN launch failure : input shape([1,64,1536,1536]) filter shape([5,5,64,32])
	 [[{{node generator/Conv2D_1}}]]
  (1) Internal: cuDNN launch failure : input shape([1,64,1536,1536]) filter shape([5,5,64,32])
	 [[{{node generator/Conv2D_1}}]]
	 [[output/_3]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cosmic/.local/lib/python3.8/site-packages/ai_benchmark/__init__.py", line 63, in run
    return run_tests(training=True, inference=True, micro=False, verbose=self.verbose,
  File "/home/cosmic/.local/lib/python3.8/site-packages/ai_benchmark/utils.py", line 583, in run_tests
    sess.run(output_, feed_dict={input_: data})
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 957, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1180, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1358, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: cuDNN launch failure : input shape([1,64,1536,1536]) filter shape([5,5,64,32])
	 [[node generator/Conv2D_1 (defined at /home/cosmic/.local/lib/python3.8/site-packages/ai_benchmark/utils.py:238) ]]
  (1) Internal: cuDNN launch failure : input shape([1,64,1536,1536]) filter shape([5,5,64,32])
	 [[node generator/Conv2D_1 (defined at /home/cosmic/.local/lib/python3.8/site-packages/ai_benchmark/utils.py:238) ]]
	 [[output/_3]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'generator/Conv2D_1':
  File "<stdin>", line 1, in <module>
  File "/home/cosmic/.local/lib/python3.8/site-packages/ai_benchmark/__init__.py", line 63, in run
    return run_tests(training=True, inference=True, micro=False, verbose=self.verbose,
  File "/home/cosmic/.local/lib/python3.8/site-packages/ai_benchmark/utils.py", line 557, in run_tests
    input_, output_, train_vars_ = getModelSrc(test, testInfo, sess)
  File "/home/cosmic/.local/lib/python3.8/site-packages/ai_benchmark/utils.py", line 238, in getModelSrc
    tf.compat.v1.train.import_meta_graph(test.model_src, clear_devices=True)
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1460, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1481, in _import_meta_graph_with_return_elements
    meta_graph.import_scoped_meta_graph_with_return_elements(
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/framework/meta_graph.py", line 794, in import_scoped_meta_graph_with_return_elements
    imported_return_elements = importer.import_graph_def(
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 400, in import_graph_def
    return _import_graph_def_internal(
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 513, in _import_graph_def_internal
    _ProcessNewOps(graph)
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/framework/importer.py", line 243, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3464, in _add_new_tf_operations
    new_ops = [
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3465, in <listcomp>
    self._create_op_from_tf_operation(c_op, compute_device=compute_devices)
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3352, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "/home/cosmic/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 1791, in __init__
    self._traceback = tf_stack.extract_stack()

>>> Memory access fault by GPU node-1 (Agent handle: 0x429bad0) on address 0x1c000. Reason: Unknown.
[oscarpc:11287] *** Process received signal ***
[oscarpc:11287] Signal: Aborted (6)
[oscarpc:11287] Signal code:  (-6)
[oscarpc:11287] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7ffb06ea4210]
[oscarpc:11287] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7ffb06ea418b]
[oscarpc:11287] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7ffb06e83859]
[oscarpc:11287] [ 3] /opt/rocm-3.5.0/lib/libhsa-runtime64.so.1(+0x55f43)[0x7ffac438ff43]
[oscarpc:11287] [ 4] /opt/rocm-3.5.0/lib/libhsa-runtime64.so.1(+0x54505)[0x7ffac438e505]
[oscarpc:11287] [ 5] /opt/rocm-3.5.0/lib/libhsa-runtime64.so.1(+0x131c7)[0x7ffac434d1c7]
[oscarpc:11287] [ 6] /lib/x86_64-linux-gnu/libpthread.so.0(+0x9609)[0x7ffb06e44609]
[oscarpc:11287] [ 7] /lib/x86_64-linux-gnu/libc.so.6(clone+0x43)[0x7ffb06f80103]
[oscarpc:11287] *** End of error message ***
Abortado (`core' generado)


dmesg

[  797.904607] amdgpu 0000:03:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:8 pasid:32779, for process python3 pid 11287 thread python3 pid 11287)
[  797.904617] amdgpu 0000:03:00.0:   in page starting at address 0x0000000000001000 from client 27
[  797.904621] amdgpu 0000:03:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00841051
[  797.904625] amdgpu 0000:03:00.0: 	 MORE_FAULTS: 0x1
[  797.904628] amdgpu 0000:03:00.0: 	 WALKER_ERROR: 0x0
[  797.904632] amdgpu 0000:03:00.0: 	 PERMISSION_FAULTS: 0x5
[  797.904635] amdgpu 0000:03:00.0: 	 MAPPING_ERROR: 0x0
[  797.904638] amdgpu 0000:03:00.0: 	 RW: 0x1
[  797.904659] amdgpu 0000:03:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:8 pasid:32779, for process python3 pid 11287 thread python3 pid 11287)
[  797.904664] amdgpu 0000:03:00.0:   in page starting at address 0x0000000000000000 from client 27
[  797.904667] amdgpu 0000:03:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[  797.904670] amdgpu 0000:03:00.0: 	 MORE_FAULTS: 0x0
[  797.904674] amdgpu 0000:03:00.0: 	 WALKER_ERROR: 0x0
[  797.904677] amdgpu 0000:03:00.0: 	 PERMISSION_FAULTS: 0x0
[  797.904680] amdgpu 0000:03:00.0: 	 MAPPING_ERROR: 0x0
[  797.904685] Evicting PASID 0x800b queues
[  797.904686] amdgpu 0000:03:00.0: 	 RW: 0x0
[  797.904702] amdgpu 0000:03:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:8 pasid:32779, for process python3 pid 11287 thread python3 pid 11287)
[  797.904707] amdgpu 0000:03:00.0:   in page starting at address 0x0000000000007000 from client 27
[  797.904710] amdgpu 0000:03:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[  797.904728] amdgpu 0000:03:00.0: 	 MORE_FAULTS: 0x0
[  797.904731] amdgpu 0000:03:00.0: 	 WALKER_ERROR: 0x0
[  797.904734] amdgpu 0000:03:00.0: 	 PERMISSION_FAULTS: 0x0
[  797.904737] amdgpu 0000:03:00.0: 	 MAPPING_ERROR: 0x0
[  797.904740] amdgpu 0000:03:00.0: 	 RW: 0x0
[  797.904757] amdgpu 0000:03:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:8 pasid:32779, for process python3 pid 11287 thread python3 pid 11287)
[  797.904761] amdgpu 0000:03:00.0:   in page starting at address 0x0000000000004000 from client 27
[  797.904764] amdgpu 0000:03:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00841051
[  797.904767] amdgpu 0000:03:00.0: 	 MORE_FAULTS: 0x1
[  797.904770] amdgpu 0000:03:00.0: 	 WALKER_ERROR: 0x0
[  797.904774] amdgpu 0000:03:00.0: 	 PERMISSION_FAULTS: 0x5
[  797.904777] amdgpu 0000:03:00.0: 	 MAPPING_ERROR: 0x0
[  797.904780] amdgpu 0000:03:00.0: 	 RW: 0x1
[  797.904805] amdgpu 0000:03:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:8 pasid:32779, for process python3 pid 11287 thread python3 pid 11287)
[  797.904809] amdgpu 0000:03:00.0:   in page starting at address 0x0000000000002000 from client 27
[  797.904812] amdgpu 0000:03:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00841051
[  797.904815] amdgpu 0000:03:00.0: 	 MORE_FAULTS: 0x1
[  797.904818] amdgpu 0000:03:00.0: 	 WALKER_ERROR: 0x0
[  797.904821] amdgpu 0000:03:00.0: 	 PERMISSION_FAULTS: 0x5
[  797.904824] amdgpu 0000:03:00.0: 	 MAPPING_ERROR: 0x0
[  797.904828] amdgpu 0000:03:00.0: 	 RW: 0x1
[  797.904843] amdgpu 0000:03:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:8 pasid:32779, for process python3 pid 11287 thread python3 pid 11287)
[  797.904847] amdgpu 0000:03:00.0:   in page starting at address 0x000000000000d000 from client 27
[  797.904850] amdgpu 0000:03:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[  797.904854] amdgpu 0000:03:00.0: 	 MORE_FAULTS: 0x0
[  797.904857] amdgpu 0000:03:00.0: 	 WALKER_ERROR: 0x0
[  797.904860] amdgpu 0000:03:00.0: 	 PERMISSION_FAULTS: 0x0
[  797.904863] amdgpu 0000:03:00.0: 	 MAPPING_ERROR: 0x0
[  797.904866] amdgpu 0000:03:00.0: 	 RW: 0x0
[  797.904891] amdgpu 0000:03:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:8 pasid:32779, for process python3 pid 11287 thread python3 pid 11287)
[  797.904895] amdgpu 0000:03:00.0:   in page starting at address 0x000000000000e000 from client 27
[  797.904898] amdgpu 0000:03:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00841051
[  797.904901] amdgpu 0000:03:00.0: 	 MORE_FAULTS: 0x1
[  797.904904] amdgpu 0000:03:00.0: 	 WALKER_ERROR: 0x0
[  797.904908] amdgpu 0000:03:00.0: 	 PERMISSION_FAULTS: 0x5
[  797.904911] amdgpu 0000:03:00.0: 	 MAPPING_ERROR: 0x0
[  797.904914] amdgpu 0000:03:00.0: 	 RW: 0x1
[  797.904931] amdgpu 0000:03:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:8 pasid:32779, for process python3 pid 11287 thread python3 pid 11287)
[  797.904935] amdgpu 0000:03:00.0:   in page starting at address 0x0000000000009000 from client 27
[  797.904938] amdgpu 0000:03:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[  797.904951] amdgpu 0000:03:00.0: 	 MORE_FAULTS: 0x0
[  797.904954] amdgpu 0000:03:00.0: 	 WALKER_ERROR: 0x0
[  797.904957] amdgpu 0000:03:00.0: 	 PERMISSION_FAULTS: 0x0
[  797.904960] amdgpu 0000:03:00.0: 	 MAPPING_ERROR: 0x0
[  797.904963] amdgpu 0000:03:00.0: 	 RW: 0x0
[  797.904982] amdgpu 0000:03:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:8 pasid:32779, for process python3 pid 11287 thread python3 pid 11287)
[  797.904985] amdgpu 0000:03:00.0:   in page starting at address 0x000000000000a000 from client 27
[  797.904989] amdgpu 0000:03:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00841051
[  797.904992] amdgpu 0000:03:00.0: 	 MORE_FAULTS: 0x1
[  797.904995] amdgpu 0000:03:00.0: 	 WALKER_ERROR: 0x0
[  797.904998] amdgpu 0000:03:00.0: 	 PERMISSION_FAULTS: 0x5
[  797.905001] amdgpu 0000:03:00.0: 	 MAPPING_ERROR: 0x0
[  797.905004] amdgpu 0000:03:00.0: 	 RW: 0x1
[  797.905022] amdgpu 0000:03:00.0: [gfxhub0] retry page fault (src_id:0 ring:0 vmid:8 pasid:32779, for process python3 pid 11287 thread python3 pid 11287)
[  797.905026] amdgpu 0000:03:00.0:   in page starting at address 0x0000000000005000 from client 27
[  797.905029] amdgpu 0000:03:00.0: VM_L2_PROTECTION_FAULT_STATUS:0x00000000
[  797.905041] amdgpu 0000:03:00.0: 	 MORE_FAULTS: 0x0
[  797.905045] amdgpu 0000:03:00.0: 	 WALKER_ERROR: 0x0
[  797.905048] amdgpu 0000:03:00.0: 	 PERMISSION_FAULTS: 0x0
[  797.905051] amdgpu 0000:03:00.0: 	 MAPPING_ERROR: 0x0
[  797.905054] amdgpu 0000:03:00.0: 	 RW: 0x0

```
